(import (scheme base))
(include "lib/imports.scm")
(include "lib/common.scm")
(include "lib/json.scm")
(include "lib/ast.scm")
(include "lib/synthesize.scm")
(include "lib/typesafe.scm")
(include "lib/report.scm")
(include "lib/trace.scm")
(include "lib/markdown.scm")
(include "lib/runtime-assess.scm")

(define (argument name args fallback)
  (let ((tail (member name args)))
    (if tail (if (pair? (cdr tail)) (cadr tail) (error "missing option value" name)) fallback)))
(define (number-option name args fallback)
  (let ((n (string->number (argument name args (number->string fallback)))))
    (unless (and n (real? n) (>= n 0) (< n +inf.0)) (error "invalid numeric option" name)) n))
(define (validate-arguments args)
  (let loop ((xs args))
    (unless (null? xs)
      (if (string=? (car xs) "--fresh") (loop (cdr xs))
        (begin
          (unless (member (car xs) '("--out" "--resume" "--target" "--max-passes" "--max-calls"
                                "--max-nodes" "--max-depth" "--max-width" "--max-literal"
                                "--batch-size" "--input-rate" "--output-rate"))
            (error "unknown option" (car xs)))
          (unless (pair? (cdr xs)) (error "missing option value" (car xs)))
          (loop (cddr xs)))))))
(define (entry name alist fallback)
  (let ((pair (assq name alist))) (if pair (cdr pair) fallback)))
(define (main args)
  (if (equal? args '("--help"))
      (begin
        (print "Usage: chibi-scheme generate.scm [--out FILE] [--fresh | --resume CHECKPOINT]")
        (print "  [--target FILE] [--max-passes 0] [--max-calls 0] [--batch-size 64]")
        (print "  Pass/call limits default to 0 (unlimited): continue until contextual approval and tests pass.")
        (print "  [--max-nodes 2048] [--max-depth 64] [--max-width 16] [--max-literal 128]")
        (print "  [--input-rate 0.042] [--output-rate 0] (USD per million tokens)")
        (print "Builds the whole AST from one hole using Jev; no interpreter template.")
        (print "Default target: targets/arithmetic.scm; output: generated/calc.scm.")
        (print "Use --target targets/r7rs-small.scm for the full interpreter (generated/interpreter.scm).")
        (print "Interrupted runs resume automatically for the same --out path; --fresh starts over.")
        (print "Every run writes trace.jsonl, report.md, checkpoint.scm and summary.scm under runs/.")
        (print "Acceptance execution requires Linux with bubblewrap and the Nix devShell."))
      (let* ((run-id (string-append (number->string (current-seconds)) "-"
                                  (number->string (current-process-id)) "-"
                                  (number->string (current-milliseconds))))
             (run-dir (string-append "runs/" run-id))
             (trace-path (string-append run-dir "/trace.jsonl"))
             (report-path (string-append run-dir "/report.md"))
             (checkpoint-path (string-append run-dir "/checkpoint.scm"))
             (target #f) (output-path #f) (resume-file #f) (published? #f))
        (ensure-directory run-dir)
        (let-values (((trace finish) (make-trace trace-path "live" 0.042 0.0
                                               (make-markdown-report report-path "live"))))
          (define (record event)
            (let ((metrics (trace event)))
              (case (car event)
                ((checkpoint)
                 (save-one checkpoint-path
                   (list (cons 'version 2) (cons 'target target) (cons 'status (cadr event))
                         (cons 'ast (caddr event)) (cons 'next-id (cadddr event))
                         (cons 'recovery-history (list-ref event 6))))
                 (unless published?
                   (save-one resume-file checkpoint-path) (set! published? #t)))
                ((response)
                 (print "Completion " (cadr event) ": " (fixed-decimal (/ (cadddr event) 1000.0) 3) "s"))
                ((completion-failed)
                 (print "Completion " (cadr event) " failed: " (fixed-decimal (/ (caddr event) 1000.0) 3) "s"))
                ((backtrack)
                 (print "Backtrack: " (datum-string (field (cadr event) "requested_from"))
                        " -> ancestor " (field (cadr event) "target")))
                ((pass)
                 (let ((feedback (car (cddddr event))))
                   (print "Pass " (cadr event) ": " (field feedback "passed") "/"
                          (field feedback "total") " tests; " (length (cadddr event))
                          " subtrees request rebaking | " (metering-text metrics)))))))
          (define (finish-run status)
            (let ((summary (finish status)))
              (save-one (string-append run-dir "/summary.scm") summary)
              (when (field summary "partial_pass_metrics" #f)
                (print "Pass " (field summary "partial_pass") " (interrupted): "
                       (metering-text (field summary "partial_pass_metrics"))))
              (print "Total (" status "): " (metering-text summary))))
          (print "Trace: " trace-path)
          (print "Report: " report-path)
          (guard (ex (else
                       (record (list 'failure (condition-text ex)))
                       (display (condition-text ex) (current-error-port)) (newline (current-error-port))
                       (when (file-exists? checkpoint-path)
                         (print "Checkpoint: " checkpoint-path)
                         (print "Rerun make generate with the same --out path to resume, or pass --resume " checkpoint-path))
                       (finish-run "failed") (exit 1)))
            (record (list 'invocation (list->vector args)))
            (validate-arguments args)
            (when (and (member "--fresh" args) (member "--resume" args))
              (error "--fresh and --resume cannot be combined"))
            (record (list 'rates (inexact (number-option "--input-rate" args 0.042))
                                (inexact (number-option "--output-rate" args 0.0))))
            (set! target (read-one (argument "--target" args "targets/arithmetic.scm")))
            (unless (and (list? target) (equal? (entry 'version target #f) 1)
                         (string? (entry 'goal target #f))
                         (memq (entry 'assessment target 'r7rs-small) '(arithmetic r7rs-small))
                         (string? (entry 'output target "generated/interpreter.scm"))
                         (list? (entry 'symbols target '())) (all? symbol? (entry 'symbols target '()))
                         (list? (entry 'literals target '()))
                         (all? (lambda (x) (or (string? x) (number? x) (char? x) (boolean? x)))
                               (entry 'literals target '())))
              (error "invalid target specification"))
            (set! output-path (argument "--out" args (entry 'output target "generated/interpreter.scm")))
            (set! resume-file (string-append output-path ".resume.scm"))
            (ensure-directory (path-directory output-path))
            (let* ((resume-path (or (argument "--resume" args #f)
                                   (and (not (member "--fresh" args)) (file-exists? resume-file) (read-one resume-file))))
                   (resume (and resume-path (read-one resume-path)))
                   (config
                    (apply object
                      (append
                        (list (cons "symbols" (entry 'symbols target '()))
                              (cons "literals" (entry 'literals target '()))
                              (cons "scheme_syntax" (eq? (entry 'assessment target 'r7rs-small) 'arithmetic))
                              (cons "runtime" (entry 'runtime target "Chibi Scheme, native R7RS-small.")))
                        (map (lambda (option)
                               (cons (car option) (number-option (cadr option) args (caddr option))))
                             '(("max_passes" "--max-passes" 0) ("max_calls" "--max-calls" 0)
                               ("max_nodes" "--max-nodes" 2048) ("max_depth" "--max-depth" 64)
                               ("max_width" "--max-width" 16) ("max_literal" "--max-literal" 128)
                               ("batch_size" "--batch-size" 64)))
                        (if resume (list (cons "ast" (entry 'ast resume #f))
                                         (cons "next_id" (entry 'next-id resume #f))
                                         (cons "recovery_history" (entry 'recovery-history resume '()))) '())))))
              (when (and resume (not (and (equal? (entry 'version resume #f) 2)
                                         (equal? target (entry 'target resume #f)))))
                (error "checkpoint version or target differs; use --fresh to start over"))
              (when resume-path (print "Resuming: " resume-path))
              (record (list 'start
                        (object (cons "description" (if resume "Resume a saved AST; all approvals will be rechecked."
                                                         "Start from scratch: one root hole, no program forms or interpreter template."))
                                (cons "goal" (entry 'goal target #f))
                                (cons "configuration" (datum-string config))
                                (cons "resume" (or resume-path 'null)))))
              (check-runtime! record)
              (let ((result (parameterize ((transport-record record))
                              (synthesize-ast (entry 'goal target #f) typesafe-oracle
                                (if (eq? (entry 'assessment target 'r7rs-small) 'arithmetic)
                                    (make-arithmetic-assessor record)
                                    (make-runtime-assessor (acceptance-cases) record)) config record))))
                (ensure-directory (path-directory output-path))
                (write-program (cdr (assq 'source result)) output-path (string-append "Jev; " trace-path))
                (record (list 'artifact output-path result))
                (when (and (file-exists? resume-file) (equal? (read-one resume-file) checkpoint-path))
                  (delete-file resume-file))
                (print "Generated: " output-path)
                (finish-run "settled"))))))))
(main (cdr (command-line)))
