;; Included by tests/run.scm; all model responses below are local fixtures.
(let* ((source (read-file-forms "tests/reference-calc.scm"))
       (target (read-one "targets/arithmetic.scm"))
       (report-dir (string-append run-dir "/arithmetic")))
  (ensure-directory report-dir)
  (progress "Constructing the arithmetic AST with a local fixture")
  (print "Arithmetic report (test fixture): " report-dir "/report.md")
  (let-values (((log done) (make-trace (string-append report-dir "/trace.jsonl") "test-fixture" 0.042 0.0
                                      (make-markdown-report (string-append report-dir "/report.md") "test-fixture"))))
    (define (events event)
      (when (and (eq? (car event) 'request) (>= (- (current-milliseconds) last-progress) 2000))
        (progress "Arithmetic fixture call " (cadr event) ": " (field (caddr event) "phase")))
      (log event))
    (log (list 'start (object (cons "description" "TEST FIXTURE: build calc from one hole; no API calls."))))
    (let* ((result (synthesize-ast (cdr (assq 'goal target)) (fixture-oracle source)
                     (make-arithmetic-assessor events)
                     (object (cons "symbols" (cdr (assq 'symbols target)))
                             (cons "scheme_syntax" #t)
                             (cons "runtime" (cdr (assq 'runtime target)))
                             (cons "max_calls" 300) (cons "max_passes" 2)) events))
           (script (string-append report-dir "/calc.scm")))
      (check 'arithmetic-constructed-from-scratch (equal? source (cdr (assq 'source result))))
      (check 'arithmetic-all-acceptance
        (= (length (arithmetic-cases)) (field (cdr (assq 'feedback result)) "passed")))
      (write-program (cdr (assq 'source result)) script "TEST FIXTURE; not Jev output.")
      (log (list 'artifact script result))
      (done "settled")
      (let ((demo (run-command (list "timeout" "-k" "1" "15" "chibi-scheme" "run-calc.scm" script)
                               (call-with-input-file "examples/arithmetic.scm" read-all))))
        (check 'arithmetic-demo (equal? demo '("7\n5\n20\n14\n21\n" "" 0))))
      (check 'arithmetic-empty-input
        (equal? (run-command (list "chibi-scheme" "run-calc.scm" script) "") '("" "" 0)))
      (check 'arithmetic-report
        (contains? (call-with-input-file (string-append report-dir "/report.md") read-all) "18/18"))))
  (progress "Checking arithmetic acceptance failures")
  (let ((assess (make-arithmetic-assessor record 2)))
    (for-each
      (lambda (bad)
        (let ((feedback (assess bad)))
          (check (list 'arithmetic-rejects bad) (< (field feedback "passed") (field feedback "total")))
          (check 'arithmetic-failure-details (> (vector-length (field feedback "failures")) 0))))
      '(((import (scheme base)) (define (calc x) 7))
        ((import (scheme base)) (define (calc x) (car x)))
        ((import (scheme base)) (define (calc x) '(wrong type)))
        ((import (scheme base)) (define other 7))
        ((import (scheme base) (scheme eval)) (define (calc x) (eval x (environment '(scheme base)))))
        ((import (rename (scheme eval) (eval hidden-eval))))
        ((import (scheme base)) (include "solution.scm")))))
  (check 'arithmetic-no-eval (arithmetic-source-problem '((eval '(+ 1 2)))))
  (progress (length (arithmetic-cases)) " arithmetic acceptance cases passed"))
