;; Test-only oracle: translates a supplied datum into generic constructor choices.
;; The live generator never loads this file or a reference implementation.
(define (answers questions decide)
  (object (cons "model" "unit-test-double")
          (cons "usage" (object (cons "input_tokens" 100) (cons "output_tokens" 0)))
          (cons "answers"
            (apply object
              (map (lambda (entry)
                     (cons (car entry) (object (cons "type" "choice")
                                              (cons "choice" (decide (symbol->string (car entry)) (cdr entry)))
                                              (cons "confidence" 1.0)))) questions)))))
(define (fixture-datum-at source path)
  (if (null? path) source
      (fixture-datum-at
        (cond ((list? source) (list-ref source (car path)))
              ((vector? source) (vector-ref source (car path)))
              ((= (car path) 0) (car source)) (else (cdr source))) (cdr path))))
(define (fixture-construct source id question)
  (let* ((target (fixture-datum-at source (with-input-from-string id read)))
         ;; This oracle already knows the target and never needs to undo its
         ;; spelling. Recovery choices are exercised by dedicated regressions.
         (plans (map (lambda (entry) (cons (symbol->string (car entry)) (with-input-from-string (cdr entry) read)))
                     (select (lambda (entry) (not (memq (car entry) '(restart backspace))))
                             (field question "criteria"))))
         (exact-atom (select (lambda (p) (equal? (cdr p) (list 'atom target))) plans)))
    (define (choose predicate)
      (let ((found (select (lambda (p) (predicate (cdr p))) plans)))
        (and (pair? found) (caar found))))
    (or (and (pair? exact-atom) (caar exact-atom))
        (cond ((list? target) (string-append "list:" (number->string (length target))))
              ((pair? target) "pair")
              ((vector? target) (string-append "vector:" (number->string (vector-length target))))
              ((symbol? target)
               (or (choose (lambda (p) (and (eq? (car p) 'tokens)
                                            (assq (cadr p) scheme-vocabulary)
                                            (memq target (cdr (assq (cadr p) scheme-vocabulary))))))
                   (and (assoc "new-symbol" plans) "new-symbol")))
              ((and (string? target) (assoc "string" plans)) "string")
              ((and (number? target) (assoc "number" plans)) "number")
              ((char? target) "character")
              (else #f))
        (let ((text (cond ((symbol? target) (symbol->string target))
                          ((number? target) (number->string target)) (else target))))
          (or (choose (lambda (p)
                        (and (eq? (car p) 'append-char)
                             (char=? (cadr p) (string-ref text (field (field question "instructions") "prefix_length"))))))
              (error "fixture cannot construct target" target plans))))))
(define (fixture-oracle source)
  (lambda (state questions)
    (answers questions
      (lambda (id q)
        (case (string->symbol (field state "phase"))
          ((construct) (fixture-construct source id q))
          ((confirm) "keep")
          (else (error "unexpected fixture revision")))))))
