;; R7RS-small acceptance probes. Runtime conformance is inherited from r7rs;
;; this suite checks that generated control flow preserves those facilities.
((empty "" "")
 (comments "; comment\n#| outer #| nested |# comment |#\n" "")
 (output "(import (scheme write)) (display \"hello\") (newline)" "hello\n")
 (order "(display \"a\") (display \"b\") (display \"c\")" "abc")
 (definitions "(define answer 40) (set! answer (+ answer 2)) (write answer)" "42")
 (false-only "(write (list (if #f 1 2) (if '() 1 2) (if 0 1 2)))" "(2 1 1)")
 (closure "(define (adder x) (lambda (y) (+ x y))) (write ((adder 7) 8))" "15")
 (tail-calls "(write (let loop ((n 10000) (a 0)) (if (= n 0) a (loop (- n 1) (+ a 1)))))" "10000")
 (hygiene "(define-syntax swap! (syntax-rules () ((_ a b) (let ((tmp a)) (set! a b) (set! b tmp))))) (let ((tmp 1) (other 2)) (swap! tmp other) (write (list tmp other)))" "(2 1)")
 (ellipsis "(define-syntax collect (syntax-rules () ((_ x ...) (list x ...)))) (write (collect 1 2 3))" "(1 2 3)")
 (local-macro "(write (let-syntax ((twice (syntax-rules () ((_ x) (+ x x))))) (twice 21)))" "42")
 (values "(write (call-with-values (lambda () (values 1 2 3)) +))" "6")
 (let-values "(write (let-values (((a b) (values 4 5))) (+ a b)))" "9")
 (define-values "(define-values (left right) (values 7 8)) (write (+ left right))" "15")
 (case-lambda "(import (scheme case-lambda)) (define f (case-lambda (() 0) ((x) x) ((x y) (+ x y)))) (write (list (f) (f 3) (f 3 4)))" "(0 3 7)")
 (continuation "(write (+ 1 (call/cc (lambda (return) (+ 8 (return 40))))))" "41")
 (dynamic-wind "(dynamic-wind (lambda () (display \"a\")) (lambda () (display \"b\")) (lambda () (display \"c\")))" "abc")
 (parameters "(define p (make-parameter 1)) (write (list (parameterize ((p 2)) (p)) (p)))" "(2 1)")
 (exceptions "(write (guard (e ((eq? e 'oops) 42)) (raise 'oops)))" "42")
 (error-objects "(write (guard (e ((error-object? e) (error-object-message e))) (error \"bad\")))" "\"bad\"")
 (records "(define-record-type point (make-point x) point? (x point-x set-point-x!)) (define pt (make-point 3)) (set-point-x! pt 8) (write (list (point? pt) (point-x pt)))" "(#t 8)")
 (promises "(import (scheme lazy)) (define times 0) (define p (delay (begin (set! times (+ times 1)) 9))) (let* ((first (force p)) (second (force p))) (write (list first second times)))" "(9 9 1)")
 (quasiquote "(write `(a ,(+ 1 2) ,@'(4 5)))" "(a 3 4 5)")
 (bytevectors "(define bytes (bytevector 1 2 255)) (bytevector-u8-set! bytes 1 9) (write (list (bytevector-length bytes) (bytevector-u8-ref bytes 1)))" "(3 9)")
 (reader-bytevector "(write (bytevector-u8-ref #u8(1 2 3) 2))" "3")
 (long-booleans "(write (list #true #false))" "(#t #f)")
 (datum-comment "#;(error \"must not run\") (write 42)" "42")
 (exact-rational "(write (+ 1/3 1/6))" "1/2")
 (large-integer "(write (= (+ 100000000000000000000 1) 100000000000000000001))" "#t")
 (string-port "(write (call-with-port (open-input-string \"abc\") (lambda (p) (read-char p))))" "#\\a")
 (library "(define-library (test example) (import (scheme base)) (export triple) (begin (define (triple x) (* 3 x)))) (import (test example)) (write (triple 7))" "21")
 (renamed-import "(import (rename (only (scheme base) +) (+ plus))) (write (plus 20 22))" "42")
 (prefixed-import "(import (prefix (only (scheme base) +) math:)) (write (math:+ 20 22))" "42")
 (cond-expand "(cond-expand (r7rs (write 'yes)) (else (write 'no)))" "yes")
 (guest-eval "(import (scheme eval)) (write (eval '(+ 20 22) (environment '(scheme base))))" "42"))
