;; Test fixture only. Never read by the live generator or sent to Jev.
(import (scheme base) (scheme read) (scheme write) (scheme eval)
        (scheme file) (chibi io)
        (only (meta) mutable-environment resolve-import module-env load-module)
        (only (chibi) %import))
(define run-r7rs
  (let ((evaluate eval) (read-datum read)
        (libraries (environment '(meta)))
        (scope (mutable-environment '(scheme base) '(scheme read) '(scheme write))))
    (lambda (text)
      (let ((input (open-input-string text)) (output (open-output-string)))
        (dynamic-wind
          (lambda () #f)
          (lambda ()
            (parameterize ((current-output-port output))
              (let loop ()
                (let ((datum (read-datum input)))
                  (unless (eof-object? datum)
                    (cond ((and (pair? datum) (eq? (car datum) 'import))
                           (for-each
                             (lambda (spec)
                               (let ((resolved (resolve-import spec)))
                                 (%import scope (module-env (load-module (car resolved))) (cdr resolved) #f)))
                             (cdr datum)))
                          ((and (pair? datum) (eq? (car datum) 'define-library)) (evaluate datum libraries))
                          (else (evaluate datum scope)))
                    (loop)))))
            (get-output-string output))
          (lambda () (close-input-port input) (close-output-port output)))))))
(define (main arguments)
  (cond ((null? arguments) (display (run-r7rs (port->string (current-input-port)))))
        ((and (= (length arguments) 2) (string=? (car arguments) "--eval"))
         (display (run-r7rs (cadr arguments))))
        ((= (length arguments) 1)
         (display (run-r7rs (call-with-input-file (car arguments) port->string))))
        (else (error "invalid arguments"))))
