(import (scheme base))
(include "lib/imports.scm")
(include "lib/common.scm")
(include "lib/json.scm")
(include "lib/ast.scm")
(include "lib/synthesize.scm")
(include "lib/report.scm")
(include "lib/trace.scm")
(include "lib/markdown.scm")
(include "tests/oracle-fixture.scm")

(define directory (string-append "runs/report-tests-" (number->string (current-seconds)) "-"
                                 (number->string (current-process-id))))
(ensure-directory directory)
(define (contains? text part)
  (let ((needle (string->list part)))
    (let loop ((chars (string->list text)))
      (and (pair? chars) (or (prefix? needle chars) (loop (cdr chars)))))))
(define checks 0)
(define (expect text phrase)
  (unless (contains? text phrase) (error "report is missing expected content" phrase))
  (set! checks (+ checks 1)))
(define (passing source) (object (cons "passed" 1) (cons "total" 1) (cons "failures" #())))
(define (exercise name oracle config)
  (let ((dir (string-append directory "/" name)))
    (ensure-directory dir)
    (let-values (((log done) (make-trace (string-append dir "/trace.jsonl") "test-fixture" 0.042 0.0
                                        (make-markdown-report (string-append dir "/report.md") "test-fixture"))))
      (define (record event)
        (when (eq? (car event) 'checkpoint) (save-one (string-append dir "/checkpoint.scm") (cdr event)))
        (log event))
      (let ((status
              (guard (ex (else (record (list 'failure (condition-text ex))) "failed"))
                (record (list 'start (object (cons "description" "Report regression test, starting from one hole.")
                                            (cons "goal" "Build one literal.")
                                            (cons "configuration" (datum-string config)))))
                (synthesize-ast "Build one literal." oracle passing config record)
                "settled")))
        (save-one (string-append dir "/summary.scm") (done status))))
    (call-with-input-file (string-append dir "/report.md") read-all)))

(let* ((base (fixture-oracle '(0)))
       (report (exercise "successful"
                 (lambda (state questions)
                   (case (string->symbol (field state "phase"))
                     ((construct) (base state questions))
                     ((revise) (answers questions (lambda (id q) "retain")))
                     (else (answers questions (lambda (id q)
                             (if (and (= 1 (field state "pass")) (string=? id "()")) "rebake" "keep"))))))
                 (object))))
  (for-each (lambda (phrase) (expect report phrase))
    '("**Status:** settled" "Needs revision" "Approved" "## Pass 1" "## Pass 2"
      "Returned choice" "Applied" "Reused 1 approvals" "Execution total" "Configuration"
      "including transport and retries")))
(let ((report (exercise "failed"
                (lambda (state questions) (error "Simulated provider failure <detail> | test")) (object))))
  (for-each (lambda (phrase) (expect report phrase))
    '("**Status:** failed" "**Stopped because:**" "Failed before review completed"
      "No model decisions were returned" "Latest checkpoint AST" "(? hole 0)"
      "usage incomplete" "Interrupted pass cost and time" "&lt;detail&gt; &#124; test"
      "**Call 1 failed after")))
(let* ((base (fixture-oracle '(0)))
       (report (exercise "limit"
                 (lambda (state questions)
                   (if (equal? (field state "phase") "construct") (base state questions)
                       (answers questions (lambda (id q) "rebake"))))
                 (object (cons "max_passes" 1)))))
  (expect report "Needs revision")
  (expect report "pass limit reached without convergence")
  (when (contains? report "Failed before review completed") (error "completed review mislabeled as interrupted")))
(let ((report (exercise "spelling-recovery"
                (lambda (state questions)
                  (answers questions (lambda (id q)
                    (cond ((equal? (field state "phase") "confirm") "keep")
                          ((assq 'end (field q "criteria")) "end")
                          (else "backspace")))))
                (object (cons "ast" '#(program (#(spell 1 number "1e"))))
                        (cons "next_id" 2) (cons "max_literal" 2) (cons "max_calls" 3)))))
  (for-each (lambda (phrase) (expect report phrase))
    '("**Status:** settled" "Construction issue at <code>(0)</code>" "Spelling length limit reached" "construct backspace")))
(let ((report (exercise "ancestor-recovery"
                (lambda (state questions)
                  (answers questions (lambda (id q)
                    (case (string->symbol (field state "phase"))
                      ((confirm) "keep") ((backtrack) "up:1")
                      (else (if (zero? (vector-length (field state "recent_abandonments")))
                                (if (equal? id "(0 1)") "backtrack" "literal:1")
                                (fixture-construct '(0) id q)))))))
                (object (cons "ast" '#(program (#(list (#(atom +) #(hole 1) #(hole 2))))))
                        (cons "next_id" 3) (cons "max_calls" 5)))))
  (for-each (lambda (phrase) (expect report phrase))
    '("**Status:** settled" "**Backtracking**" "ancestor <code>(0)</code>"
      "Recovery history: abandoned" "Discarded batched choice" "construct literal:1")))
(let ((report (exercise "construction-cycle"
                (lambda (state questions)
                  (answers questions (lambda (id q)
                    (case (string->symbol (field state "phase"))
                      ((confirm) "keep") ((backtrack) "up:1")
                      (else
                       (if (pair? (select (lambda (e) (equal? (field e "action") "backtrack"))
                                         (vector->list (field state "recent_abandonments"))))
                           (fixture-construct '(0) id q)
                           (if (field (field q "instructions") "prefix" #f) "restart" "new-symbol")))))))
                (object (cons "ast" '#(program (#(hole 1)))) (cons "next_id" 2) (cons "max_calls" 15)))))
  (for-each (lambda (phrase) (expect report phrase))
    '("**Status:** settled" "Construction cycle detected" "identical AST shape three times" "**Backtracking**")))
(print checks " report assertions passed. Example reports: " directory "/")
