(import (scheme base))
(include "lib/imports.scm")
(include "lib/common.scm")
(include "lib/json.scm")
(include "lib/ast.scm")
(include "lib/runtime-assess.scm")
(define (check name value) (unless value (error "restart test failed" name)))
(define (fixture-ast x root?)
  (cond ((list? x) (vector (if root? 'program 'list) (map (lambda (v) (fixture-ast v #f)) x)))
        ((pair? x) (vector 'pair (fixture-ast (car x) #f) (fixture-ast (cdr x) #f)))
        ((vector? x) (vector 'vector (map (lambda (v) (fixture-ast v #f)) (vector->list x))))
        (else (vector 'atom x))))
(define (read-trace checkpoint)
  (call-with-input-file (string-append (path-directory checkpoint) "/trace.jsonl")
    (lambda (port)
      (let loop ((events '()))
        (let ((c (peek-char port)))
          (cond ((eof-object? c) (reverse events))
                ((char-whitespace? c) (read-char port) (loop events))
                (else (loop (cons (native-json-read port) events)))))))))
(define (of-kind kind events) (select (lambda (e) (equal? kind (field e "event"))) events))

(print "Restart tests use a local curl fixture; no API calls. The 429 test includes 7s of retry backoff.")
(call-with-scratch
  (lambda (directory)
    (let* ((output (string-append directory "/interpreter.scm"))
           (pointer (string-append output ".resume.scm"))
           (seed (string-append directory "/seed.scm"))
           (spec (string-append directory "/target.scm"))
           (count (string-append directory "/count"))
           (bin (string-append directory "/bin"))
           (target (read-one "targets/r7rs-small.scm"))
           (source (read-file-forms "tests/reference-program.scm"))
           (history (list (object (cons "path" "(0)") (cons "action" "backtrack") (cons "source" "(old-choice ?)"))))
           (ast (fixture-ast source #t)))
      (define (invoke key mode . options)
        (run-command
          (append (list "timeout" "-k" "1" "40" "env"
                        (string-append "PATH=" bin ":" (get-environment-variable "PATH"))
                        (string-append "TYPESAFE_API_KEY=" key) "TYPESAFE_MODEL=test-fixture"
                        (string-append "SKIBIDU_FIXTURE_MODE=" mode) (string-append "SKIBIDU_FIXTURE_COUNT=" count)
                        "chibi-scheme" "generate.scm")
                  (if spec (list "--target" spec) '()) (if output (list "--out" output) '()) options) ""))
      ;; Label the generated reports without adding a test mode to the CLI.
      (set-cdr! (assq 'goal target) "TEST FIXTURE ONLY: local curl stub; no API requests or charges.")
      (save-one spec target)
      (save-one seed (list (cons 'version 2) (cons 'target target) (cons 'status 'checking)
                          (cons 'ast ast) (cons 'next-id 1) (cons 'recovery-history history)))
      (ensure-directory bin)
      (call-with-output-file (string-append bin "/curl")
        (lambda (p)
          (display "#!/bin/sh\nexec chibi-scheme " p)
          (display (shell-quote (string-append (current-directory) "/tests/curl-fixture.scm")) p)
          (display " \"$@\"\n" p)))
      (check 'fixture-executable (zero? (caddr (run-command (list "chmod" "+x" (string-append bin "/curl")) ""))))
      (save-one pointer seed)
      (let ((fresh (invoke "" "keep" "--fresh")))
        (check 'fresh-fails-without-key (= 1 (caddr fresh)))
        (check 'fresh-ignores-saved-ast (equal? '#(hole 0) (cdr (assq 'ast (read-one (read-one pointer)))))))
      (save-one pointer seed)
      (let* ((failed (invoke "test-fixture" "429"))
             (checkpoint (read-one pointer)) (events (read-trace checkpoint))
             (failure (car (of-kind "completion-failed" events)))
             (attempts (of-kind "http-result" events)))
        (check 'rate-limit-fails (= 1 (caddr failed)))
        (check 'accepted-completion-before-failure (= 1 (length (of-kind "response" events))))
        (check 'four-rate-limit-attempts (= 5 (length attempts)))
        (check 'only-http-rate-limit-failures
          (equal? '(200 429 429 429 429) (map (lambda (e) (field (field e "details") "status")) attempts)))
        (check 'transport-succeeded (all? (lambda (e) (zero? (field (field e "details") "curl_exit"))) attempts))
        (check 'three-backoffs (= 3 (length (of-kind "http-retry" events))))
        (check 'successful-completion-timed (> (field (car (of-kind "response" events)) "duration_ms") 0))
        (check 'checkpoint-survives (equal? ast (cdr (assq 'ast (read-one checkpoint)))))
        (check 'history-survives (equal? history (cdr (assq 'recovery-history (read-one checkpoint)))))
        (check 'history-in-resumed-prompt
          (equal? (list->vector history) (field (field (car (of-kind "request" events)) "state") "recent_abandonments")))
        (check 'completion-includes-attempt-time
          (>= (field failure "duration_ms")
              (+ 7000 (apply + (map (lambda (event) (field (field event "details") "duration_ms")) (cdr attempts))))))
        (print "429 failure and timing verified. Resuming with the same output path.")
        (let* ((resumed (invoke "test-fixture" "keep"))
               (lines (with-input-from-string (car resumed) (lambda ()
                        (let loop ((out '()))
                          (let ((line (read-line))) (if (eof-object? line) (reverse out) (loop (cons line out)))))))))
          (check 'resume-succeeds (zero? (caddr resumed)))
          (check 'resume-announced (member (string-append "Resuming: " checkpoint) lines))
          (check 'pointer-cleared (not (file-exists? pointer)))
          (check 'artifact-preserved (equal? source (read-file-forms output)))
          (check 'previous-trace-preserved (file-exists? (string-append (path-directory checkpoint) "/trace.jsonl")))
          (for-each (lambda (line) (when (or (prefix? (string->list "Report:") (string->list line))
                                            (prefix? (string->list "Completion") (string->list line))) (print line))) lines)))
      (print "Checking default arithmetic target and separate resume paths in a temporary checkout.")
      (let ((original-directory (current-directory)))
        (call-with-scratch
          (lambda (work)
            (check 'copy-default-fixture
              (zero? (caddr (run-command (list "cp" "-R" "generate.scm" "lib" "targets" "tests" work) ""))))
            (set! spec #f) (set! output #f)
            (dynamic-wind
              (lambda () (change-directory work))
              (lambda ()
                (ensure-directory "generated")
                (save-one "generated/interpreter.scm.resume.scm" seed)
                (check 'default-fresh-needs-key (= 1 (caddr (invoke "" "keep" "--fresh"))))
                (let* ((checkpoint (read-one "generated/calc.scm.resume.scm"))
                       (saved (read-one checkpoint))
                       (calc-source (read-file-forms "tests/reference-calc.scm")))
                  (check 'default-target (equal? (cdr (assq 'target saved)) (read-one "targets/arithmetic.scm")))
                  (check 'default-starts-empty (equal? '#(hole 0) (cdr (assq 'ast saved))))
                  ;; Seed only this local integration fixture; production starts from the hole above.
                  (set-cdr! (assq 'ast saved) (fixture-ast calc-source #t))
                  (save-one checkpoint saved)
                  (check 'default-resume-succeeds (zero? (caddr (invoke "test-fixture" "keep"))))
                  (check 'default-artifact (equal? calc-source (read-file-forms "generated/calc.scm")))
                  (check 'default-pointer-cleared (not (file-exists? "generated/calc.scm.resume.scm")))
                  (check 'legacy-pointer-untouched (equal? seed (read-one "generated/interpreter.scm.resume.scm")))))
              (lambda () (change-directory original-directory)))))))))
(print "Automatic restart, fresh start, HTTP retries, completion timings, checkpoint cleanup, and arithmetic defaults passed.")
