(import (scheme base))
(include "lib/imports.scm")
(include "lib/common.scm")
(include "lib/json.scm")
(include "lib/ast.scm")
(include "lib/synthesize.scm")
(include "lib/report.scm")
(include "lib/trace.scm")
(include "lib/markdown.scm")
(include "lib/runtime-assess.scm")
(include "tests/oracle-fixture.scm")

(define run-dir (string-append "runs/tests-" (number->string (current-seconds)) "-"
                              (number->string (current-process-id))))
(ensure-directory run-dir)
(define-values (record finish) (make-trace (string-append run-dir "/trace.jsonl") "test" 0.042 0.0))
(define checks 0)
(define started (current-milliseconds))
(define last-progress started)
(define (progress . message)
  (set! last-progress (current-milliseconds))
  (display "[") (display (fixed-decimal (/ (- last-progress started) 1000.0) 1)) (display "s] ")
  (apply print message))
(define (check name ok)
  (record (list 'assertion name (and ok #t)))
  (unless ok (error "test assertion failed" name))
  (set! checks (+ checks 1)))
(define (raises? thunk) (guard (ex (else #t)) (thunk) #f))
(define (passing source) (object (cons "passed" 1) (cons "total" 1) (cons "failures" #())))
(define (contains? text part)
  (let ((needle (string->list part)))
    (let loop ((chars (string->list text)))
      (and (pair? chars) (or (prefix? needle chars) (loop (cdr chars)))))))
(define (exercise oracle assess config)
  (let ((events '()))
    (let ((result (synthesize-ast "unit test" oracle assess config
                    (lambda (event) (set! events (cons event events)) (record event)))))
      (list result (reverse events)))))
(define (times-asked id events)
  (length (select (lambda (e) (and (eq? (car e) 'request) (equal? (field (caddr e) "phase") "confirm")
                                  (assq (json-key id) (cadddr e)))) events)))
(define tiny-tree '#(program (#(atom 0) #(atom 0))))
(define (tiny-config . entries) (apply object (cons (cons "ast" tiny-tree) entries)))
(define (tiny-oracle rejection revision)
  (lambda (state questions)
    (answers questions
      (lambda (id q)
        (case (string->symbol (field state "phase"))
          ((confirm) (if (rejection (field state "pass") id) "rebake" "keep"))
          ((revise) (revision (field state "pass") id))
          ((construct) (fixture-construct '(1 0) id q)))))))

(guard (ex (else (record (list 'failure (condition-text ex))) (finish "failed")
                 (print (condition-text ex)) (print "Trace: " run-dir "/trace.jsonl") (exit 1)))
  (print "Local tests only; no model/API calls. Trace: " run-dir "/trace.jsonl")
  (progress "Checking JSON, subprocesses, and AST construction/revision")
  (let* ((data (object (cons "text" "quotes\" slash\\ tab\t newline\n λ😀")
                       (cons "array" (vector #t #f 'null 12 -3 0.5 (object)))))
         (copy (json-read (json-string data))))
    (check 'json-roundtrip (equal? data copy))
    (check 'json-surrogate (equal? (json-read "\"\\ud83d\\ude00\"") "😀"))
    (check 'unicode-truncation (equal? (short-text "a😀bc" 2) "a😀..."))
    (check 'json-reject-nonfinite (raises? (lambda () (json-string +inf.0))))
    (for-each (lambda (bad) (check (list 'json-reject bad) (raises? (lambda () (json-read bad)))))
              '("{\"a\":1,\"a\":2}" "[1,]" "true false" "1e9999")))
  (check 'process-exit-code (equal? (run-command '("sh" "-c" "exit 7") "") '("" "" 7)))
  (check 'process-quoting (equal? (run-command '("printf" "%s" "a'`$() b") "") '("a'`$() b" "" 0)))
  (check 'invalid-root (raises? (lambda () (validate-ast '#(atom 42) 20 20))))
  (check 'duplicate-holes (raises? (lambda () (validate-ast '#(program (#(hole 1) #(hole 1))) 20 20))))
  (check 'operator-before-arguments
    (equal? (map car (ast-frontier '#(program (#(list (#(hole 1) #(hole 2) #(hole 3))))))) '((0 0))))
  (check 'independent-arguments-batched
    (equal? (map car (ast-frontier '#(program (#(list (#(atom +) #(hole 2) #(hole 3))))))) '((0 1) (0 2))))
  (let ()
    (define (options kind text limit)
      (ast-options (vector 'program (list (vector 'spell 1 kind text))) '(0) '() '() 64 16 limit))
    (check 'identifier-cannot-start-with-digit (not (assoc "char:52" (options 'symbol "" 128))))
    (check 'identifier-cannot-contain-parenthesis (not (assoc "char:40" (options 'symbol "x" 128))))
    (check 'identifier-can-contain-digit (assoc "char:48" (options 'symbol "x" 128)))
    (check 'peculiar-identifier-prefix (assoc "char:97" (options 'symbol "." 128)))
    (check 'string-can-contain-parenthesis (assoc "char:40" (options 'string "" 128)))
    (for-each
      (lambda (kind)
        (let ((choices (options kind (make-string 128 #\() 128)))
          (check (list 'limited-token-can-restart kind) (assoc "restart" choices))
          (check (list 'limited-token-can-backspace kind) (assoc "backspace" choices))
          (check (list 'limited-token-cannot-grow kind) (not (assoc "char:40" choices)))))
      '(symbol number string))
    (check 'valid-token-at-limit-can-finish (assoc "end" (options 'symbol "x" 1)))
    (check 'invalid-number-cannot-finish (not (assoc "end" (options 'number "(" 1))))
    (check 'empty-token-group-can-restart
      (assoc "restart" (ast-options '#(program (#(token 1 seen #f))) '(0) '() '() 64 16 128))))
  ;; Reproduce the saved live failure at (1), then let the oracle restart just
  ;; that node. The first completed sibling and pending node ID must survive.
  (let* ((bad-text (string-append "40" (make-string 126 (integer->char 40))))
         (stuck (vector 'spell 4 'symbol bad-text))
         (tree (vector 'program (list '#(atom 0) stuck)))
         (run (exercise
                (lambda (state questions)
                  (answers questions
                    (lambda (id q)
                      (cond ((equal? (field state "phase") "confirm") "keep")
                            ((field (field q "instructions") "construction_problem" #f) "restart")
                            (else (fixture-construct '(0 x) id q))))))
                passing (object (cons "ast" tree) (cons "next_id" 5) (cons "max_calls" 10)))))
    (check 'stuck-checkpoint-recovers (equal? '(0 x) (cdr (assq 'source (car run)))))
    (check 'restart-preserves-node-id
      (equal? '#(hole 4) (ast-construct '(restart) stuck #f (lambda () (error "unexpected new hole"))))))
  (let ((run (exercise
               (lambda (state questions)
                 (answers questions (lambda (id q)
                   (if (equal? (field state "phase") "confirm") "keep"
                       (if (assq 'end (field q "criteria")) "end" "backspace")))))
               passing (object (cons "ast" '#(program (#(spell 1 number "1e"))))
                               (cons "next_id" 2) (cons "max_literal" 2) (cons "max_calls" 3)))))
    (check 'backspace-repairs-invalid-number (equal? '(1) (cdr (assq 'source (car run))))))
  (let* ((source '((define (invented-name x) (cons "hello" (cons #\q '(2 . 3)))) #(1 #f)))
         (run (exercise (fixture-oracle source) passing (object))))
    (check 'whole-ast-from-hole (equal? source (cdr (assq 'source (car run)))))
    (check 'initial-checkpoint-is-one-hole
      (equal? '#(hole 0) (caddr (cadr (cadr run)))))
    (check 'no-preinstalled-imports (not (assq 'import (cdr (assq 'source (car run)))))))
  (let* ((run (exercise (tiny-oracle (lambda (pass id) (and (= pass 1) (string=? id "(0)")))
                                   (lambda (pass id) "replace")) passing (tiny-config)))
         (events (cadr run)))
    (check 'revision-changes-atom (equal? (cdr (assq 'source (car run))) '(1 0)))
    (check 'sibling-reconfirmed (= 2 (times-asked "(1)" events)))
    (check 'root-reconfirmed (= 2 (times-asked "()" events))))
  (let ((run (exercise (tiny-oracle (lambda (pass id) (and (< pass 3) (string=? id "(0)")))
                                  (lambda (pass id) "retain")) passing (tiny-config))))
    (check 'explicit-third-pass-approval (= 3 (cdr (assq 'passes (car run)))))
    (check 'retaining-is-not-approval (= 3 (times-asked "(0)" (cadr run))))
    (check 'unchanged-context-caches-sibling (= 1 (times-asked "(1)" (cadr run)))))
  (let* ((assessment 0)
         (run (exercise (tiny-oracle (lambda (pass id) (and (= pass 1) (string=? id "(0)")))
                                    (lambda (pass id) "retain"))
                (lambda (source) (set! assessment (+ assessment 1))
                  (object (cons "passed" 1) (cons "total" 1) (cons "revision" assessment) (cons "failures" #())))
                (tiny-config))))
    (check 'changed-test-context-invalidates (= 2 (times-asked "(1)" (cadr run)))))
  (let* ((seen '())
         (base (tiny-oracle (lambda (pass id) #f) (lambda (pass id) (if (string=? id "()") "descend:0" "replace"))))
         (run (exercise (lambda (s q)
                          (when (= 0 (field (field s "test_feedback") "passed" -1))
                            (set! seen (cons (field s "phase") seen))) (base s q))
                (lambda (source)
                  (if (= (car source) 1) (passing source)
                      (object (cons "passed" 0) (cons "total" 1)
                              (cons "failures" (vector (object (cons "name" "value") (cons "error" "wrong value")))))))
                (tiny-config))))
    (check 'failure-fed-to-confirm (member "confirm" seen))
    (check 'failure-fed-to-revise (member "revise" seen))
    (check 'failure-fed-to-construct (member "construct" seen))
    (check 'approvals-cannot-override-failures (= 2 (cdr (assq 'passes (car run))))))
  (for-each
    (lambda (config)
      (check (list 'limit config)
        (raises? (lambda () (exercise (fixture-oracle '((+ 1 2))) passing config)))))
    (list (object (cons "max_calls" 1)) (object (cons "max_nodes" 2))
          (object (cons "max_calls" -1)) (object (cons "max_passes" -1))
          (object (cons "ast" '#(program (#(hole 4)))) (cons "next_id" 3))))
  (check 'zero-budgets-allow-convergence
    (= 3 (cdr (assq 'passes (car
      (exercise (tiny-oracle (lambda (p id) (< p 3)) (lambda (p id) "retain"))
                passing (tiny-config (cons "max_calls" 0) (cons "max_passes" 0))))))))
  (check 'pass-limit
    (raises? (lambda () (exercise (tiny-oracle (lambda (p id) #t) (lambda (p id) "retain"))
                                  passing (tiny-config (cons "max_passes" 1))))))
  (check 'invalid-answer
    (raises? (lambda () (exercise (lambda (s q) (answers q (lambda (id question) "absent"))) passing (object)))))

  (progress "Checking backtracking, recovery history, and compact prompts")
  (include "tests/backtrack-cases.scm")
  (progress "Checking regressions from the live arithmetic trace")
  (include "tests/trace-regressions.scm")
  (progress "Checking token and cost accounting")
  (let-values (((log done) (make-trace (string-append run-dir "/metering.jsonl") "synthetic" 2.0 3.0)))
    (log (list 'request 1 (object) (object)))
    (log (list 'response 1 (object (cons "usage" (object (cons "input_tokens" 100) (cons "output_tokens" 50))))))
    (let ((first (log (list 'pass 1 1 '() (passing #f)))))
      (check 'pass-one-tokens (= 150 (field first "reported_total_tokens")))
      (check 'pass-one-cost (< (abs (- 0.00035 (field first "estimated_usd_for_reported_usage"))) 1e-12))
      (log (list 'request 2 (object) (object)))
      (log (list 'response 2 (object (cons "usage" (object (cons "input_tokens" 40) (cons "output_tokens" 10))))))
      (let* ((second (log (list 'pass 2 1 '() (passing #f)))) (summary (done "tested")))
        (check 'pass-two-is-delta (= 50 (field second "reported_total_tokens")))
        (check 'pass-two-cost (< (abs (- 0.00011 (field second "estimated_usd_for_reported_usage"))) 1e-12))
        (check 'metered-cost (< (abs (- 0.00046 (field summary "estimated_usd_for_reported_usage"))) 1e-12))
        (check 'metering-complete (field summary "usage_complete"))
        (check 'total-time-covers-passes
          (>= (field summary "duration_ms") (+ (field first "duration_ms") (field second "duration_ms")))))))
  (let-values (((log done) (make-trace (string-append run-dir "/missing-usage.jsonl") "synthetic" 2.0 3.0)))
    (log '(pass-start 1 "test")) (log (list 'request 1 (object) (object)))
    (let ((summary (done "failed")))
      (check 'missing-usage-is-unknown (not (field summary "usage_complete")))
      (check 'interrupted-pass-metered (= 1 (field (field summary "partial_pass_metrics") "calls")))))
  (check 'markdown-escapes (equal? (md-text "a|<b>`") "a&#124;&lt;b&gt;&#96;"))

  (progress "Checking the Chibi sandbox")
  (check-runtime! record)
  (include "tests/arithmetic.scm")
  (let* ((source (read-file-forms "tests/reference-program.scm"))
         (report-dir (string-append run-dir "/full-ast")))
    (ensure-directory report-dir)
    (print "Full AST report (test fixture): " report-dir "/report.md")
    (let-values (((log done) (make-trace (string-append report-dir "/trace.jsonl") "test-fixture" 0.042 0.0
                                        (make-markdown-report (string-append report-dir "/report.md") "test-fixture"))))
      (define (events event)
        (when (eq? (car event) 'checkpoint) (save-one (string-append report-dir "/checkpoint.scm") (cdr event)))
        (let ((result (log event)))
          (case (car event)
            ((pass-start) (progress "Fixture pass " (cadr event) ": " (caddr event)))
            ((request)
             (when (>= (- (current-milliseconds) last-progress) 2000)
               (progress "Fixture call " (cadr event) ": " (field (caddr event) "phase"))))
            ((test-execution) (progress "Running the 47 runtime acceptance cases"))
            ((cli-test-execution)
             (when (>= (- (current-milliseconds) last-progress) 2000)
               (progress "Checking the interpreter CLI in the sandbox")))
            ((pass)
             (let ((feedback (car (cddddr event))))
               (progress "Fixture pass " (cadr event) ": " (field feedback "passed") "/"
                         (field feedback "total") " acceptance cases passed"))))
          result))
      (log (list 'start (object (cons "description" "Build a test reference program from one hole using typed fixture choices."))))
      (let* ((base (fixture-oracle source))
             (oracle (lambda (s q)
                       (if (equal? (field s "phase") "construct") (base s q)
                           (answers q (lambda (id question)
                             (if (equal? (field s "phase") "revise") "retain"
                                 (if (and (= (field s "pass") 1) (string=? id "()")) "rebake" "keep")))))))
             (result (synthesize-ast "test fixture only" oracle (make-runtime-assessor (acceptance-cases) events)
                       (object (cons "max_calls" 1500) (cons "max_passes" 2)) events))
             (script (string-append report-dir "/interpreter.scm")))
        (check 'runtime-all-acceptance (= (length (acceptance-cases)) (field (cdr (assq 'feedback result)) "passed")))
        (check 'entire-program-constructed (equal? source (cdr (assq 'source result))))
        (check 'full-program-multipass (= 2 (cdr (assq 'passes result))))
        (write-program (cdr (assq 'source result)) script "TEST FIXTURE; not Jev output.")
        (log (list 'artifact script result))
        (done "settled")
        (progress "Checking the completed report and standalone launcher")
        (let ((report (call-with-input-file (string-append report-dir "/report.md") read-all)))
          (for-each (lambda (phrase) (check (list 'report phrase) (contains? report phrase)))
                    '("## Pass 1" "## Pass 2" "Execution total" "Returned choice" "Applied" "Reused" "Test fixture")))
        (for-each
          (lambda (test)
            (let ((result (run-command (append (list "timeout" "-k" "1" "15" "chibi-scheme" "run.scm" script)
                                               (car test)) (cadr test))))
              (record (list 'cli-result test result))
              (check (list 'cli test) (and (= 0 (caddr result)) (equal? (car result) (caddr test))))))
          '((("examples/demo.scm") "" "(42 42)\n") (("--eval" "(write (+ 20 22))") "" "42")
            (() "" "") (() "(write 42)" "42")))
        (check 'cli-errors-propagate
          (not (= 0 (caddr (run-command (list "timeout" "-k" "1" "15" "chibi-scheme" "run.scm" script "--eval" "(error \"expected\")") "")))))
        (print "Full AST report (test fixture): " report-dir "/report.md"))))
  (record (list 'test-summary checks)) (finish "passed")
  (progress checks " assertions passed. All " (length (acceptance-cases)) " runtime acceptance cases passed.")
  (print "Trace: " run-dir "/trace.jsonl"))
