;; Regressions from the live arithmetic trace: (cal cc), ignored root
;; rejections, repeated spelling restarts and duplicated worker failures.
(let ()
  (define (options tree path . width)
    (scheme-syntax-options tree path '(calc)
      (ast-options tree path '(calc) '() 64 (if (null? width) 16 (car width)) 128)))
  (let ((root (options '#(hole 0) '()))
        (top (options '#(program (#(hole 1))) '(0))))
    (check 'declaration-program-nonempty (not (assoc "list:0" root)))
    (check 'top-level-cannot-be-bare-import (all? (lambda (p) (eq? 'list (cadr p))) top))
    (check 'top-level-requires-head-and-content (not (assoc "list:1" top)))
    (check 'top-level-can-be-import-or-definition (and (assoc "list:2" top) (assoc "list:3" top))))
  (let* ((tree '#(program (#(list (#(atom import) #(hole 1))))))
         (choices (options tree '(0 1))))
    (check 'import-set-is-a-pair-of-library-names (equal? choices '(("list:2" list 2)))))
  (let* ((tree '#(program (#(list (#(atom define) #(hole 1) #(hole 2))))))
         (choices (options tree '(0 1))))
    (check 'known-api-name-needs-no-spelling (assoc "known:0" choices))
    (check 'definition-target-can-be-signature (assoc "list:2" choices))
    (check 'definition-target-cannot-be-number (not (assoc "number" choices)))
    (check 'maximum-width-with-known-names-fits-api (<= (length (options tree '(0 2) 96)) 254)))
  (let* ((tree '#(program (#(list (#(atom define) #(atom calc) #(hole 1))))))
         (choices (options tree '(0 2))))
    (check 'body-cannot-be-bare-syntax-keyword (not (assoc "symbols:syntax" choices)))
    (check 'body-can-be-a-compound-expression (assoc "list:4" choices)))
  (let ((tree '#(program (#(list (#(atom define) #(atom calc) #(list (#(hole 1) #(hole 2) #(hole 3) #(hole 4)))))))))
    (check 'expression-head-can-be-syntax-keyword (assoc "symbols:syntax" (options tree '(0 2 0)))))
  (let ((tree '#(program (#(list (#(atom define) #(atom calc) #(list (#(atom quote) #(hole 1)))))))))
    (check 'quoted-keywords-still-allowed (assoc "symbols:syntax" (options tree '(0 2 1)))))
  (let* ((tree '#(program (#(list (#(atom import) #(list (#(atom scheme) #(atom base)))))
                                  #(list (#(hole 1) #(hole 2) #(hole 3))))))
         (choices (options tree '(1 0))))
    (check 'declaration-keywords-equally-visible
      (equal? (map caddr choices) '(import define begin)))
    (check 'declaration-keyword-has-no-hidden-group (= 3 (length choices))))
  (check 'cycle-comparison-ignores-fresh-hole-ids
    (equal? (ast-construction-key '#(program (#(list (#(atom import) #(hole 1) #(hole 2))))))
            (ast-construction-key '#(program (#(list (#(atom import) #(hole 34) #(hole 35)))))))))
(let* ((run (exercise
              (lambda (state questions)
                (answers questions (lambda (id q)
                  (case (string->symbol (field state "phase"))
                    ((confirm) (if (= 1 (field state "pass")) "rebake" "keep"))
                    ((revise)
                     (check 'rejected-root-gets-edit (string=? id "()")) "replace")
                    (else (fixture-construct '((quote 1)) id q))))))
              passing (object (cons "ast" '#(program (#(atom cal) #(atom cc))))
                              (cons "max_calls" 20))))
       (requests (select (lambda (e) (eq? (car e) 'request)) (cadr run))))
  (check 'parent-repair-completes (equal? '((quote 1)) (cdr (assq 'source (car run)))))
  (let* ((request (car (select (lambda (e) (equal? (field (caddr e) "phase") "construct")) requests)))
         (q (cdar (cadddr request))))
    (check 'construction-is-an-explicit-question
      (contains? (field (field q "instructions") "question") "Choose what to BUILD"))
    (check 'root-is-program-container
      (contains? (field (field q "instructions") "role") "Program container"))
    (check 'root-arity-explained (contains? (field (field q "criteria") "list:2") "2 top-level forms"))))
(let ((run (exercise
             (lambda (state questions)
               (answers questions (lambda (id q)
                 (case (string->symbol (field state "phase"))
                   ((confirm) (if (and (= 1 (field state "pass")) (member id '("(0)" "(0 1)"))) "rebake" "keep"))
                   ((revise) (if (string=? id "(0)") "descend:1" "replace"))
                   (else (fixture-construct '((+ 0 1) 4) id q))))))
             passing (object (cons "ast" '#(program (#(list (#(atom +) #(atom bad) #(atom 1))) #(atom 4))))
                             (cons "max_calls" 10)))))
  (check 'parent-can-choose-small-edit
    (pair? (select (lambda (e) (equal? e '(edit-descent (0) 1))) (cadr run))))
  (check 'parent-descent-preserves-sibling (equal? '((+ 0 1) 4) (cdr (assq 'source (car run))))))

(for-each
  (lambda (spelling?)
    (let* ((tree (if spelling? '#(program (#(spell 17 symbol "ca"))) '#(program (#(atom calc) #(hole 17)))))
           (run (exercise
                  (lambda (state questions)
                    (answers questions (lambda (id q)
                      (case (string->symbol (field state "phase"))
                        ((confirm) "keep")
                        ((backtrack)
                         (check 'cycle-explained-to-model
                           (contains? (field (field q "instructions") "construction_problem") "identical AST"))
                         "up:1")
                        (else
                         (if (pair? (select (lambda (entry) (equal? (field entry "action") "backtrack"))
                                           (vector->list (field state "recent_abandonments"))))
                             (fixture-construct '(0) id q)
                             (let ((prefix (field (field q "instructions") "prefix" #f)))
                               (if spelling? (if (equal? prefix "ca") "char:99" "backspace")
                                   (cond ((not prefix) "new-symbol") ((string=? prefix "") "char:99")
                                         (else "restart"))))))))))
                  passing (object (cons "ast" tree) (cons "next_id" 18) (cons "max_calls" 20)))))
      (check (list 'cycle-recovers spelling?) (equal? '(0) (cdr (assq 'source (car run)))))
      (check 'cycle-recorded (= 1 (length (select (lambda (e) (eq? (car e) 'construction-cycle)) (cadr run)))))))
  '(#f #t))

(let* ((failures (list->vector
                  (append
                    (map (lambda (i) (object (cons "name" (number->string i)) (cons "actual" 'null)
                                            (cons "error" "worker failed: ERROR: undefined variable: calc")))
                         (integers-from 0 18))
                    (list (object (cons "name" "wrong-value") (cons "actual" "0") (cons "expected" "7") (cons "error" 'null))
                          (object (cons "name" "wrong-value-two") (cons "actual" "0") (cons "expected" "19") (cons "error" 'null))))))
       (feedback (object (cons "passed" 0) (cons "total" 20) (cons "failures" failures)))
       (compact (compact-feedback feedback)))
  (check 'worker-errors-grouped (= 3 (vector-length (field compact "failures"))))
  (check 'worker-error-count (= 18 (field (vector-ref (field compact "failures") 0) "same_error_case_count")))
  (check 'grouped-count-reported (= 17 (field compact "duplicate_failure_count")))
  (check 'distinct-failures-preserved (= 0 (field compact "additional_failure_count")))
  (check 'exhaustive-feedback-unmodified (not (field (vector-ref failures 0) "same_error_case_count" #f)))
  (check 'feedback-payload-smaller (< (string-length (json-string compact)) (/ (string-length (json-string feedback)) 2))))
