(define (all? predicate xs)
  (or (null? xs) (and (predicate (car xs)) (all? predicate (cdr xs)))))
(define (select predicate xs)
  (cond ((null? xs) '()) ((predicate (car xs)) (cons (car xs) (select predicate (cdr xs))))
        (else (select predicate (cdr xs)))))
(define (string-index s c)
  (let loop ((i 0))
    (and (< i (string-length s))
         (if (char=? (string-ref s i) c) i (loop (+ i 1))))))
(define (prefix? a b)
  (or (null? a) (and (pair? b) (equal? (car a) (car b)) (prefix? (cdr a) (cdr b)))))
(define (take-up-to xs n)
  (if (or (zero? n) (null? xs)) '() (cons (car xs) (take-up-to (cdr xs) (- n 1)))))
(define (batches xs n)
  (let loop ((xs xs) (current '()) (size 0) (out '()))
    (cond ((null? xs) (reverse (if (null? current) out (cons (reverse current) out))))
          ((= size n) (loop xs '() 0 (cons (reverse current) out)))
          (else (loop (cdr xs) (cons (car xs) current) (+ size 1) out)))))
(define (condition-text ex)
  (if (error-object? ex)
      (string-append (error-object-message ex) " " (datum-string (error-object-irritants ex)))
      (datum-string ex)))
(define (read-all port)
  (let loop ((chunks '()))
    (let ((chunk (read-string 8192 port)))
      (if (eof-object? chunk) (apply string-append (reverse chunks)) (loop (cons chunk chunks))))))
(define (print . xs) (for-each display xs) (newline) (flush-output-port))
(define (fail location message . irritants)
  (apply error (string-append (symbol->string location) ": " message) irritants))
(define (with-output-to-string thunk)
  (let ((port (open-output-string)))
    (parameterize ((current-output-port port)) (thunk))
    (get-output-string port)))
(define (with-input-from-string text thunk)
  (call-with-port (open-input-string text)
    (lambda (port) (parameterize ((current-input-port port)) (thunk)))))
(define (pretty-print x . ports) (show (if (null? ports) (current-output-port) (car ports)) (pretty x)))
(define (current-milliseconds) (quotient (* 1000 (current-jiffy)) (jiffies-per-second)))
(define (delete-file* path) (when (file-exists? path) (delete-file path)))
(define (ensure-directory path)
  (unless (create-directory* path) (error "could not create directory" path)))
(define (path-directory path)
  (let loop ((i (- (string-length path) 1)))
    (cond ((< i 0) ".") ((char=? #\/ (string-ref path i)) (if (= i 0) "/" (substring path 0 i)))
          (else (loop (- i 1))))))
(define (atomic-write path writer)
  (let ((temporary (string-append path ".tmp-" (number->string (current-process-id)))))
    (dynamic-wind (lambda () #f)
      (lambda ()
        (call-with-output-file temporary writer)
        (unless (rename-file temporary path) (error "could not replace file" path)))
      (lambda () (delete-file* temporary)))))
(define (read-one path)
  (call-with-input-file path
    (lambda (port)
      (let ((x (read port)))
        (unless (eof-object? (read port)) (error "expected one datum" path)) x))))
;; Checkpoints are machine-readable state, often written hundreds of times.
;; Avoid pretty-printing the entire growing AST on every construction step.
(define (save-one path datum)
  (atomic-write path (lambda (p) (write datum p) (newline p))))
(define (call-with-scratch thunk)
  (call-with-temp-dir "skibidu"
    (lambda (directory preserve)
      (preserve)
      (dynamic-wind (lambda () #f) (lambda () (thunk directory))
                    (lambda () (delete-file-hierarchy directory))))))
(define (shell-quote text)
  (string-append "'"
    (with-output-to-string
      (lambda ()
        (string-for-each
          (lambda (c) (if (char=? c #\') (display "'\\''") (write-char c))) text)))
    "'"))
(define (short-text s limit)
  (if (<= (string-length s) limit) s (string-append (substring s 0 limit) "...")))
(define (join-strings xs separator)
  (if (null? xs) "" (apply string-append (car xs) (map (lambda (s) (string-append separator s)) (cdr xs)))))
;; File-backed stdout/stderr avoid pipe deadlocks. The input is deliberately
;; not logged here: curl authentication is supplied through its stdin.
(define (run-command command input)
  (call-with-scratch
    (lambda (directory)
      (let* ((out-path (string-append directory "/stdout"))
             (err-path (string-append directory "/stderr"))
             (shell (string-append "exec " (join-strings (map shell-quote command) " ")
                                   " >" (shell-quote out-path) " 2>" (shell-quote err-path))))
        (call-with-process-io (list "sh" "-c" shell)
          (lambda (pid in out err)
            (display input in) (close-output-port in)
            (close-input-port out) (close-input-port err)
            (let ((status (waitpid pid 0)))
              (list (call-with-input-file out-path read-all)
                    (call-with-input-file err-path read-all)
                    (if (zero? (modulo (cadr status) 256))
                        (quotient (cadr status) 256)
                        (+ 128 (modulo (cadr status) 128)))))))))))
(define (compact-feedback feedback)
  ;; A load failure prevents every case from running. Keep one representative
  ;; per identical worker error instead of repeating the same stack eight times.
  ;; Ordinary value mismatches and per-input exceptions remain independent.
  (define (worker-error failure)
    (let ((message (field failure "error" #f)))
      (and (eq? (field failure "actual" #f) 'null) (string? message)
           (prefix? (string->list "worker failed:") (string->list message)) message)))
  (if (not (field feedback "failures" #f)) feedback
      (let* ((failures (vector->list (field feedback "failures")))
             (unique (let loop ((xs failures) (seen '()) (out '()))
                       (if (null? xs) (reverse out)
                           (let ((message (worker-error (car xs))))
                             (if (and message (member message seen)) (loop (cdr xs) seen out)
                                 (loop (cdr xs) (if message (cons message seen) seen)
                                       (cons (if message
                                                 (append (car xs)
                                                   (list (cons 'same_error_case_count
                                                           (length (select (lambda (f) (equal? message (worker-error f))) failures)))))
                                                 (car xs)) out)))))))
             (first (take-up-to unique 8)))
        (object (cons "passed" (field feedback "passed"))
                (cons "total" (field feedback "total"))
                (cons "failures"
                      (list->vector
                       (map (lambda (failure)
                              (apply object
                                (map (lambda (entry)
                                       (cons (car entry)
                                             (if (string? (cdr entry))
                                                 (short-text (cdr entry) 700)
                                                 (cdr entry))))
                                     failure))) first)))
                (cons "duplicate_failure_count" (- (length failures) (length unique)))
                (cons "additional_failure_count" (- (length unique) (length first)))))))
