(import (scheme base) (scheme case-lambda) (scheme char) (scheme cxr)
        (scheme eval) (scheme file) (scheme inexact) (scheme load)
        (scheme process-context) (scheme read) (scheme repl) (scheme time) (scheme write)
        (only (chibi filesystem) create-directory* rename-file delete-file-hierarchy
              current-directory change-directory)
        (only (chibi process) call-with-process-io waitpid current-process-id sleep)
        (only (chibi temp-file) call-with-temp-dir)
        (only (chibi time) current-seconds seconds->string)
        (rename (only (chibi json) json-read json-write json->string)
                (json-read native-json-read) (json->string json-string))
        (srfi 166) (srfi 166 pretty))
