;; Deterministic reporting from the same events as the exhaustive JSONL trace.
;; No model calls, inferred motives, or hidden reasoning are added by reporting.
(define (md-text value)
  (let ((text (if (string? value) value (datum-string value))))
    (with-output-to-string
      (lambda ()
        (string-for-each
          (lambda (c)
            (display (case c ((#\&) "&amp;") ((#\<) "&lt;") ((#\>) "&gt;")
                       ((#\|) "&#124;") ((#\`) "&#96;") ((#\*) "&#42;")
                       ((#\_) "&#95;") ((#\[) "&#91;") ((#\]) "&#93;")
                       ((#\\) "&#92;") ((#\newline) "<br>") ((#\return) "")
                       (else (string c))))) text)))))
(define (md-code value) (string-append "<code>" (md-text value) "</code>"))
(define (md-fence language text)
  (let loop ((chars (string->list text)) (run 0) (longest 2))
    (if (null? chars)
        (let ((fence (make-string (+ longest 1) #\`)))
          (string-append "\n" fence language "\n" text "\n" fence "\n\n"))
        (let ((next (if (char=? (car chars) #\`) (+ run 1) 0)))
          (loop (cdr chars) next (max longest next))))))
(define (md-row cells) (display "| ") (display (join-strings cells " | ")) (display " |\n"))
(define (md-table headers rows)
  (newline) (md-row headers) (md-row (map (lambda (x) "---") headers))
  (for-each md-row rows) (newline))
(define (make-markdown-report path mode)
  (let ((body (open-output-string)) (status "Running") (passes '()) (summary #f)
        (requests '()) (current-pass 0) (pass-finished? #f)
        (failure-reason #f) (last-action "Preparing the run") (last-checkpoint #f) (pending-call #f)
        (input-rate 0.042) (output-rate 0.0) (last-source #f) (last-time 0) (last-save 0))
    (define (data event)
      (with-input-from-string (field event "data_scheme") read))
    (define (stamp event)
      (display "\nAt +") (display (fixed-decimal (/ (field event "elapsed_ms") 1000.0) 3))
      (display "s · trace event #") (display (field event "seq")) (display ".\n\n"))
    (define (details label language text)
      (display "\n<details><summary>") (display (md-text label)) (display "</summary>\n")
      (display (md-fence language text)) (display "</details>\n\n"))
    (define (feedback-text feedback)
      (if (field feedback "passed" #f)
          (string-append (number->string (field feedback "passed")) "/"
                         (number->string (field feedback "total")) " acceptance tests passed")
          "No acceptance results yet"))
    (define (overview-row number outcome acceptance rejected metrics)
      (list (string-append "[" (number->string number) "](#pass-" (number->string number) ")")
            outcome acceptance rejected (number->string (field metrics "calls"))
            (string-append (number->string (field metrics "reported_input_tokens")) " / "
                           (number->string (field metrics "reported_output_tokens")))
            (string-append "$" (fixed-decimal (field metrics "estimated_usd_for_reported_usage") 8)
                           (if (field metrics "usage_complete") "" " (incomplete)"))
            (string-append (fixed-decimal (/ (field metrics "duration_ms") 1000.0) 3) "s")))
    (define (save!)
      (atomic-write path
        (lambda (port)
          (parameterize ((current-output-port port))
            (display "# AST generation report\n\n")
            (display "**Status:** ") (display status) (display " · **Mode:** ")
            (display (md-text mode)) (display " · **Last event:** +")
            (display (fixed-decimal (/ last-time 1000.0) 3)) (display "s\n\n")
            (when failure-reason
              (display "**Stopped because:** ") (display (md-text (short-text failure-reason 500))) (display "\n\n"))
            (display "**Last action:** ") (display (md-text last-action)) (display "\n\n")
            (when summary (display "**Total:** ") (display (md-text (metering-text summary))) (display "\n\n"))
            (display "[Exhaustive JSONL trace](trace.jsonl)")
            (when (file-exists? (string-append (path-directory path) "/checkpoint.scm"))
              (display " · [Resume checkpoint](checkpoint.scm)"))
            (display "\n\n")
            (display "This report records returned model decisions, applied AST edits, and test observations. Jev returns choices and confidence, not prose reasoning. Reporting uses no extra model tokens.\n\n")
            (when (not (string=? mode "live"))
              (display "**Test fixture: these decisions are not evidence of a live Jev generation.**\n\n"))
            (when (or (pair? passes) (and summary (field summary "partial_pass_metrics" #f)))
              (display "## Pass overview\n")
              (md-table '("Pass" "Outcome" "Tests passed" "Rejected subtrees" "Calls" "Input / output tokens" "Estimated USD" "Time")
                (append
                  (map (lambda (event)
                         (let* ((feedback (field event "feedback"))
                                (rejected (vector-length (field event "rejected_paths"))))
                           (overview-row (field event "number")
                             (if (and (= rejected 0) (= (field feedback "passed") (field feedback "total")))
                                 "Approved" "Needs revision")
                             (string-append (number->string (field feedback "passed")) "/"
                                            (number->string (field feedback "total")))
                             (number->string rejected) (field event "metrics")))) (reverse passes))
                  (if (and summary (field summary "partial_pass_metrics" #f))
                      (list (overview-row (field summary "partial_pass") "Failed before review completed" "—" "—"
                                          (field summary "partial_pass_metrics"))) '()))))
            (when (and (> current-pass 0) (not pass-finished?))
              (display "Pass ") (display current-pass)
              (display (if summary " stopped before completing its review. Its recorded work is below.\n\n"
                                   " is in progress. The report refreshes during execution and at every pass boundary.\n\n")))
            (display (get-output-string body))))))
    (define (consume event)
      (set! last-time (field event "elapsed_ms"))
      (parameterize ((current-output-port body))
        (let ((kind (field event "event")))
          (cond
            ((string=? kind "rates")
             (set! input-rate (field event "input_usd_per_million"))
             (set! output-rate (field event "output_usd_per_million")))
            ((string=? kind "start")
             (display "## Starting point\n\n")
             (let ((info (car (data event))))
               (display (md-text (field info "description" "Generation started."))) (newline)
               (when (field info "goal" #f)
                 (display "\n**Goal:** ") (display (md-text (field info "goal"))) (display "\n\n"))
               (when (string? (field info "resume" #f))
                 (display "\nResumed from ") (display (md-code (field info "resume")))
                 (display ". Costs and timings in this report cover this execution. Earlier traces and reports are preserved.\n\n"))
               (when (field info "configuration" #f)
                 (details "Configuration" "scheme"
                   (with-output-to-string
                     (lambda () (pretty-print (with-input-from-string (field info "configuration") read))))))))
            ((string=? kind "pass-start")
             (let ((info (data event)))
               (set! current-pass (car info)) (set! pass-finished? #f)
               (set! last-action (cadr info))
               (display "\n<a id=\"pass-") (display current-pass) (display "\"></a>\n\n## Pass ")
               (display current-pass) (newline) (stamp event)
               (display (md-text (cadr info))) (display "\n\n")))
            ((string=? kind "request")
             (let* ((id (field event "call")) (state (field event "state"))
                    (questions (field event "questions")) (feedback (field state "test_feedback")))
               (set! requests (cons (cons id event) requests))
               (set! pending-call id)
               (set! last-action (string-append "Waiting for Jev call " (number->string id) " (" (field state "phase") ")."))
               (display "### Call ") (display id) (display " — ")
               (display (md-text (field state "phase"))) (newline) (stamp event)
               (display "Sent ") (display (length questions)) (display " questions with the complete current AST. ")
               (display (md-text (feedback-text feedback))) (display ".\n\n")
               (for-each
                 (lambda (entry)
                   (let ((problem (field (field (cdr entry) "instructions") "construction_problem" #f)))
                     (when problem
                       (display "Construction issue at ") (display (md-code (symbol->string (car entry))))
                       (display ": ") (display (md-text problem)) (display "\n\n")))) questions)
               (when (field feedback "failures" #f)
                 (let ((names (map (lambda (f) (field f "name" "unnamed"))
                                   (vector->list (field feedback "failures")))))
                   (unless (null? names)
                     (display "Failures fed back: ") (display (md-text (join-strings names ", ")))
                     (display ". Further failures omitted from this prompt: ")
                     (display (field feedback "additional_failure_count" 0))
                     (when (> (field feedback "duplicate_failure_count" 0) 0)
                       (display "; repeated worker errors grouped: ")
                       (display (field feedback "duplicate_failure_count")))
                     (display ".\n\n"))))
               (display "The trace contains this call's exact context and every offered alternative.\n\n")))
            ((string=? kind "construction-cycle")
             (display "**Construction cycle detected:** the same AST shape was visited three times. Asking Jev to choose an ancestor to rebuild at ")
             (display (md-code (field (car (data event)) "path"))) (display ".\n\n"))
            ((string=? kind "response")
             (let* ((id (field event "call")) (request (cdr (assv id requests)))
                    (response (field event "response")) (answers (field response "answers" (object)))
                    (usage (field response "usage" #f)))
               (set! pending-call #f)
               ;; The rendered body already preserves past decisions. Keeping
               ;; every question/alternative here makes the GC workload grow
               ;; throughout a run; retain only unanswered requests.
               (set! requests (select (lambda (entry) (not (= id (car entry)))) requests))
               (set! last-action (string-append "Jev call " (number->string id) " returned "
                                                (number->string (length answers)) " decisions."))
               (display "**Call ") (display id) (display " returned** from ")
               (display (md-code (field response "model" "unspecified model")))
               (display " after ")
               (display (fixed-decimal (/ (field event "duration_ms") 1000.0) 3))
               (display "s, including transport and retries. ")
               (if (and usage (number? (field usage "input_tokens" #f)) (number? (field usage "output_tokens" #f)))
                   (begin (display (field usage "input_tokens")) (display " input / ")
                          (display (field usage "output_tokens")) (display " output tokens; estimated $")
                          (display (fixed-decimal (/ (+ (* input-rate (field usage "input_tokens"))
                                                       (* output-rate (field usage "output_tokens"))) 1000000.0) 8)))
                   (display "Usage was not reported"))
               (display ".\n")
               (md-table '("AST path" "Target" "Returned choice" "Meaning" "Confidence")
                 (map (lambda (entry)
                        (let* ((q (cdr entry)) (instruction (field q "instructions"))
                               (answer (field answers (car entry) (object)))
                               (choice (field answer "choice" "missing"))
                               (confidence (field answer "confidence" #f)))
                          (list (md-code (field instruction "path" (car entry)))
                                (md-code (short-text (field instruction "node" "") 90))
                                (md-code choice)
                                (md-text (field (field q "criteria") choice "Invalid or missing answer"))
                                (if (number? confidence) (string-append (fixed-decimal (* 100 confidence) 1) "%") "unknown"))))
                      (field request "questions")))))
            ((string=? kind "edit")
             (let ((edit (car (data event))))
               (display "Applied ") (display (md-code (field edit "action")))
               (display " at ") (display (md-code (field edit "path"))) (display ": ")
               (display (md-code (short-text (field edit "before") 180))) (display " → ")
               (display (md-code (short-text (field edit "after") 180))) (display ".\n\n")))
            ((string=? kind "backtrack")
             (let ((info (car (data event))))
               (display "**Backtracking** from ") (display (md-code (field info "requested_from")))
               (display " to ancestor ") (display (md-code (field info "target")))
               (display "; rebuild that subtree before continuing construction.\n\n")))
            ((string=? kind "abandoned")
             (let ((info (car (data event))))
               (display "Recovery history: abandoned ") (display (md-code (field info "source")))
               (display " at ") (display (md-code (field info "path")))
               (display " via ") (display (md-code (field info "action"))) (display ".\n\n")))
            ((string=? kind "discarded-choice")
             (let ((info (car (data event))))
               (display "Discarded batched choice ") (display (md-code (field info "choice")))
               (display " at ") (display (md-code (field info "path")))
               (display " because an ancestor was rebuilt.\n\n")))
            ((string=? kind "retained")
             (display "Retained ") (display (md-code (car (data event))))
             (display " without editing. This does not approve it; it must be reviewed again.\n\n"))
            ((string=? kind "edit-descent")
             (let ((info (data event)))
               (display "Jev narrowed the edit from ") (display (md-code (car info)))
               (display " to child ") (display (cadr info)) (display ".\n\n")))
            ((string=? kind "assessment")
             (let* ((info (data event)) (feedback (car info)) (source (cadr info)))
               (set! last-action (feedback-text feedback))
               (display "### Candidate and acceptance tests\n") (stamp event)
               (if (equal? source last-source)
                   (display "The candidate source is unchanged from the previous pass.\n\n")
                   (details "Complete candidate source" "scheme"
                            (with-output-to-string (lambda () (for-each pretty-print source)))))
               (set! last-source source)
               (display "**") (display (md-text (feedback-text feedback))) (display ".**\n\n")
               (for-each
                 (lambda (failure)
                   (details (string-append "Failure: " (field failure "name" "unnamed")) "scheme"
                     (with-output-to-string (lambda () (pretty-print failure)))))
                 (vector->list (field feedback "failures" #())))))
            ((string=? kind "invalidate-confirmations")
             (display "Invalidated ") (display (car (data event)))
             (display " earlier approvals because the AST or test context changed.\n\n"))
            ((string=? kind "reuse-confirmations")
             (display "Reused ") (display (car (data event)))
             (display " approvals whose complete AST and test context are unchanged.\n\n"))
            ((string=? kind "http-attempt")
             (let ((info (field event "details")))
               (display "HTTP attempt ") (display (field info "attempt")) (display " using ")
               (display (md-code (field info "model"))) (display ".\n\n")))
            ((string=? kind "http-result")
             (let ((info (field event "details")))
               (display "HTTP status ") (display (field info "status"))
               (display "; curl exit ") (display (field info "curl_exit"))
               (display "; attempt time ") (display (fixed-decimal (/ (field info "duration_ms") 1000.0) 3))
               (display "s.\n\n")
               (unless (<= 200 (field info "status") 299)
                 (details "Provider or transport failure" "text"
                          (string-append (field info "body" "") "\n" (field info "stderr" ""))))))
            ((string=? kind "http-retry")
             (display "Retry backoff: ") (display (cadr (data event))) (display "s.\n\n"))
            ((string=? kind "completion-failed")
             (set! last-action (string-append "Jev call " (number->string (field event "call")) " failed."))
             (display "**Call ") (display (field event "call")) (display " failed after ")
             (display (fixed-decimal (/ (field event "duration_ms") 1000.0) 3))
             (display "s**, including transport, retries, and backoff.\n\n"))
            ((string=? kind "pass")
             (set! passes (cons event passes)) (set! pass-finished? #t)
             (set! last-action (string-append "Completed review of pass " (number->string (field event "number")) "."))
             (display "### Pass result\n\n")
             (let ((rejected (field event "rejected_paths")) (feedback (field event "feedback")))
               (cond ((> (vector-length rejected) 0)
                      (display "Jev requested rebaking of ") (display (vector-length rejected))
                      (display " subtrees: ") (display (md-code (vector->list rejected))) (display ".\n\n"))
                     ((< (field feedback "passed") (field feedback "total"))
                      (display "Every subtree was approved, but acceptance failures prevent convergence.\n\n"))
                     (else (display "Every subtree has a current explicit keep approval and all acceptance tests pass.\n\n"))))
             (display "**") (display (md-text (metering-text (field event "metrics")))) (display ".**\n\n"))
            ((string=? kind "failure")
             (set! status "Failed") (set! failure-reason (car (data event)))
             (display "### Execution stopped\n") (stamp event)
             (display (md-fence "text" failure-reason))
             (when pending-call
               (let ((questions (field (cdar requests) "questions")))
                 (display "No model decisions were returned for the pending call. It was asked to decide:\n")
                 (md-table '("AST path" "Action" "Target")
                   (map (lambda (entry)
                          (let ((i (field (cdr entry) "instructions")))
                            (list (md-code (field i "path")) (md-text (field i "action"))
                                  (md-code (field i "node"))))) questions))))
             (when last-checkpoint
               (details "Latest checkpoint AST (question marks mark unfinished nodes)" "scheme"
                 (with-output-to-string
                   (lambda () (pretty-print (ast-datum (cadr (with-input-from-string last-checkpoint read)))))))))
            ;; Preserve the serialized snapshot; decode it only if a failure
            ;; needs it in the report, not on every construction step.
            ((string=? kind "checkpoint") (set! last-checkpoint (field event "data_scheme")))
            ((string=? kind "artifact")
             (display "Generated artifact: ") (display (md-code (car (data event)))) (display ".\n\n"))
            ((string=? kind "summary")
             (set! summary event) (set! status (field event "status"))
             (when (field event "partial_pass_metrics" #f)
               (display "\n### Interrupted pass cost and time\n\n")
               (display (md-text (metering-text (field event "partial_pass_metrics")))) (display ".\n\n"))
             (display "\n## Execution total\n\n")
             (display (md-text (metering-text event))) (display ".\n\n")
             (display "Pass 1 includes initial construction. Later passes include revisions since the preceding review, tests, and confirmation. Total time includes reporting and artifact I/O before the summary.\n\n")))))
      ;; Keep every event in the report body and JSONL trace, but coalesce
      ;; rapid progress refreshes. Important boundaries always flush at once.
      (when (or (>= (- last-time last-save) 500)
                (member (field event "event")
                        '("start" "pass-start" "assessment" "pass" "completion-failed" "failure" "artifact" "summary")))
        (save!) (set! last-save last-time)))
    (save!)
    consume))
