(define (read-file-forms path)
  (call-with-input-file path
    (lambda (p)
      (let loop ((xs '()))
        (let ((x (read p))) (if (eof-object? x) (reverse xs) (loop (cons x xs))))))))
(define (write-program source path provenance)
  (atomic-write path
    (lambda (port)
      (display "; " port) (display provenance port) (newline port)
      ;; Deliberately no automatically inserted imports, evaluator, or CLI.
      (for-each (lambda (form) (pretty-print form port)) source))))
(define (sandbox-command directory seconds script)
  (append (list "timeout" "-k" "1" (number->string seconds)
                "bwrap" "--unshare-all" "--die-with-parent" "--new-session" "--clearenv"
                "--setenv" "PATH" (or (get-environment-variable "PATH") "")
                "--ro-bind" "/nix/store" "/nix/store" "--proc" "/proc" "--dev" "/dev"
                "--tmpfs" "/tmp" "--bind" directory "/work" "--chdir" "/work"
                "--" "chibi-scheme") script))
(define (check-runtime! record)
  (call-with-scratch
    (lambda (directory)
      (let* ((command (sandbox-command directory 15
                        '("-e" "(begin (import (scheme base) (scheme write)) (display 42))")))
             (result (run-command command "")))
        (record (list 'runtime-probe command result))
        (unless (and (= 0 (caddr result)) (string=? (car result) "42"))
          (error "Chibi test sandbox is unavailable" result))))))
(define (acceptance-cases)
  (append
    (map (lambda (test) (cons 'run test))
         (append (read-one "tests/r7rs-cases.scm") (read-one "tests/r7rs-regressions.scm")))
    '((error-run propagated-error "(error \"expected\")" "raises")
      (run output-closed "(define saved-output (current-output-port))" "")
      (run output-closed-check "(write (output-port-open? saved-output))" "#f")
      (main cli-eval ("--eval" "(write (+ 20 22))") "42")
      (stdin cli-stdin "(write (+ 20 22))" "42")
      (stdin cli-empty "" "")
      (main cli-file ("program.scm") "42")
      (error-main cli-bad-arguments ("one" "two" "three") "raises"))))
(define (make-runtime-assessor cases record . time-limit)
  (lambda (source)
    (call-with-scratch
      (lambda (directory)
        (let ((candidate (string-append directory "/candidate.scm"))
              (worker (string-append directory "/worker.scm")))
          (write-program source candidate "Candidate constructed by model decisions.")
          (unless (assq 'calc cases)
            (write-program (read-file-forms "run.scm") (string-append directory "/launcher.scm")
                           "The actual CLI launcher, exercised in a fresh process.")
            (call-with-output-file (string-append directory "/program.scm")
              (lambda (p) (display "(import (scheme base) (scheme write)) (write (+ 20 22))" p))))
          (write-program
            `((import (scheme base) (scheme cxr) (scheme eval) (scheme load) (scheme write)
                      (only (meta) mutable-environment))
              (define scope (mutable-environment '(rename (only (meta) repl-import) (repl-import import))))
              (load "candidate.scm" scope)
              (define run (eval ',(if (assq 'calc cases) 'calc 'run-r7rs) scope))
              (for-each
                (lambda (test)
                  (let ((actual #f) (failure #f) (kind (car test)))
                    (guard (ex (else (set! failure
                                       (if (error-object? ex) (error-object-message ex)
                                           (let ((p (open-output-string))) (write ex p) (get-output-string p))))))
                      (set! actual (run (caddr test))))
                    (write (list (cadr test)
                                 (if (memq kind '(error-run error-main)) (and failure #t)
                                     (and (not failure) (equal? actual (cadddr test))))
                                 actual failure))
                    (newline) (flush-output-port)))
                ',(select (lambda (test) (memq (car test) '(calc run error-run))) cases)))
            worker "Isolated acceptance harness; not part of the generated artifact.")
          (let ((command (sandbox-command directory (if (null? time-limit) 15 (car time-limit)) '("worker.scm"))))
            (record (list 'test-execution
                          (object (cons "command" (list->vector command))
                                  (cons "candidate" (call-with-input-file candidate read-all))
                                  (cons "harness" (call-with-input-file worker read-all)))))
            (let* ((result (run-command command "")) (stdout (car result)) (stderr (cadr result))
                   (rows (guard (ex (else '()))
                           (with-input-from-string stdout
                             (lambda ()
                               (let loop ((xs '()))
                                 (let ((x (read)))
                                   (if (eof-object? x) (reverse xs)
                                       (if (and (list? x) (= 4 (length x)) (symbol? (car x)))
                                           (loop (cons x xs)) (error "invalid test output")))))))))
                   (passed 0) (failures '()))
              (record (list 'test-process-result
                            (object (cons "stdout" stdout) (cons "stderr" stderr) (cons "exit_code" (caddr result)))))
              (for-each
                (lambda (test)
                  (let* ((row
                           (if (memq (car test) '(calc run error-run)) (assq (cadr test) rows)
                               (let* ((command (sandbox-command directory
                                                  (if (null? time-limit) 15 (car time-limit))
                                                  (append '("launcher.scm" "candidate.scm")
                                                          (if (eq? (car test) 'stdin) '() (caddr test)))))
                                      (input (if (eq? (car test) 'stdin) (caddr test) "")))
                                 (record (list 'cli-test-execution command input))
                                 (let* ((result (run-command command input))
                                        (ok (if (eq? (car test) 'error-main) (not (zero? (caddr result)))
                                                (and (zero? (caddr result)) (equal? (car result) (cadddr test))))))
                                   (record (list 'cli-test-result result))
                                   (list (cadr test) ok (car result)
                                         (if (zero? (caddr result)) #f (cadr result)))))))
                         (ok (and row (cadr row)))
                         (item (object (cons "name" (symbol->string (cadr test)))
                                       (cons "kind" (symbol->string (car test)))
                                       (cons "program" (if (string? (caddr test)) (caddr test) (datum-string (caddr test))))
                                       (cons "expected" (if (eq? (car test) 'calc) (datum-string (cadddr test)) (cadddr test)))
                                       (cons "actual" (if row (if (eq? (car test) 'calc) (datum-string (caddr row)) (caddr row)) 'null))
                                       (cons "error" (if row (or (cadddr row) 'null)
                                                          (string-append "worker failed: " stderr)))
                                       (cons "passed" (and ok #t)))))
                    (record (list 'test-case item))
                    (if ok (set! passed (+ passed 1)) (set! failures (cons item failures))))) cases)
              (when (and (= passed (length cases)) (not (zero? (caddr result))))
                (set! passed (- passed 1))
                (set! failures (cons (object (cons "name" "worker-exit") (cons "error" stderr)) failures)))
              (object (cons "passed" passed) (cons "total" (length cases))
                      (cons "failures" (list->vector (reverse failures)))))))))))

(define (arithmetic-cases)
  (append (read-one "tests/arithmetic-cases.scm")
          (list (list 'calc 'deep-recursion
                      (let loop ((n 40) (x 0))
                        (if (zero? n) x (loop (- n 1) (list '+ 1 x)))) 40))))
(define (arithmetic-source-problem source)
  (let walk ((x source))
    (cond ((pair? x)
           (if (eq? (car x) 'import)
               (and (not (equal? x '(import (scheme base)))) "Only (import (scheme base)) is allowed.")
               (or (walk (car x)) (walk (cdr x)))))
          ((memq x '(eval load include include-ci))
           "Implement dispatch and recursion yourself; eval, load and include are not allowed.")
          (else #f))))
(define (make-arithmetic-assessor record . time-limit)
  (let ((assess (apply make-runtime-assessor (arithmetic-cases) record time-limit)))
    (lambda (source)
      (let ((problem (arithmetic-source-problem source)))
        (if (not problem) (assess source)
            (let ((failure (object (cons "name" "allowed-runtime") (cons "kind" "source")
                                   (cons "program" (datum-string source))
                                   (cons "expected" "Only (scheme base), with your own dispatch and recursion.")
                                   (cons "actual" 'null) (cons "error" problem) (cons "passed" #f))))
              (record (list 'test-case failure))
              (object (cons "passed" 0) (cons "total" (length (arithmetic-cases)))
                      (cons "failures" (vector failure)))))))))
