;; Construct the entire program AST through typed decisions. There is no seed
;; implementation, fixed evaluator skeleton, or table of solution fragments.
(define (synthesize-ast goal oracle assess config record)
  (let* ((tree (field config "ast" (vector 'hole 0)))
         (next-id (field config "next_id" 1))
         (max-passes (field config "max_passes" 0))
         (max-calls (field config "max_calls" 0))
         (max-nodes (field config "max_nodes" 2048))
         (max-depth (field config "max_depth" 64))
         (max-width (field config "max_width" 16))
         (max-literal (field config "max_literal" 128))
         (batch-size (field config "batch_size" 64))
         (symbols (field config "symbols" '())) (literals (field config "literals" '()))
         (scheme-syntax? (field config "scheme_syntax" #f))
         (calls 0) (pass-number 1) (construction-issue #f)
         (feedback (object (cons "status" "not tested yet")))
         (history (take-up-to (field config "recovery_history" '()) 8))
         (confirmed-tree #f) (confirmed-feedback #f) (confirmed-history #f) (confirmed-paths '()))
    (define (checkpoint status)
      (record (list 'checkpoint status tree next-id calls feedback history)))
    (define (hole)
      (let ((node (vector 'hole next-id))) (set! next-id (+ next-id 1)) node))
    (define (context phase)
      (object
        (cons "goal" goal) (cons "phase" phase) (cons "pass" pass-number)
        (cons "source" (datum-string (ast-datum tree)))
        (cons "runtime" (field config "runtime" "Chibi Scheme, R7RS-small. Generate all imports yourself."))
        (cons "test_feedback" (compact-feedback feedback))
        (cons "test_feedback_scope" "Tests describe the last completed candidate, before any current construction or revisions.")
        (cons "recent_abandonments" (list->vector history))
        (cons "rules"
          "Build the whole AST. Source is a list of top-level forms; (? ...) marks unexpanded nodes, not Scheme code. Paths are zero-based AST child indices, including program forms; a pair has car/cdr children 0/1. Constructors make ONE node with holes as children. Spelling builds one identifier or literal, never Scheme source; backspace removes a character, restart rebuilds this node from a hole. During construction, backtrack lets you choose an ancestor to rebuild immediately; up:1 means parent. Recent abandonments describe earlier contexts: avoid repeating those dead ends, but they are not forbidden choices. Seen symbols are names already in the AST, not necessarily in scope. Every token and list is reviewed in complete context. A keep decision explicitly means no change is wanted here. All approvals expire when source, feedback, or recovery history changes.")))
    (define (ask phase questions)
      (when (and (> max-calls 0) (>= calls max-calls))
        (checkpoint 'call-limit) (error "model call limit reached before convergence" max-calls))
      (set! calls (+ calls 1))
      (let ((state (context phase)))
        (record (list 'request calls state questions))
        (let* ((started (current-milliseconds))
               (response (guard (ex (else
                                      (record (list 'completion-failed calls (- (current-milliseconds) started)
                                                    (condition-text ex)))
                                      (raise ex)))
                           (oracle state questions)))
               (duration (- (current-milliseconds) started)))
          (record (list 'response calls response duration))
          (let ((answers (field response "answers")))
            (for-each
              (lambda (entry)
                (let* ((answer (field answers (car entry))) (choice (field answer "choice"))
                       (confidence (field answer "confidence")))
                  (unless (and (equal? (field answer "type") "choice") (string? choice)
                               (assq (json-key choice) (field (cdr entry) "criteria"))
                               (real? confidence) (<= 0 confidence 1))
                    (error "invalid typed model answer" (car entry))))) questions)
            answers))))
    (define (question action path node options)
      (when (or (null? options) (> (length options) 255))
        (error "question must have between 1 and 255 options" path))
      (object (cons "type" "choice")
              (cons "instructions"
                    (apply object
                      (append (list (cons "action" action)
                                    (cons "question"
                                      (cond ((string=? action "construct")
                                             "Which next construction step best advances a correct program satisfying the goal? Choose what to BUILD, not what the unfinished node currently resembles. Reuse vocabulary names when available. Constructor lengths count all children, including the operator.")
                                            ((string=? action "confirm")
                                             "Should this subtree remain unchanged in the complete program, considering the goal and test failures? Approve only if no change is wanted here.")
                                            ((string=? action "revise")
                                             "Which edit fixes this rejected subtree in context? Descend for a local fix; replace or change children when the enclosing structure is wrong.")
                                            (else "Which ancestor must be rebuilt to escape this construction dead end?")))
                                    (cons "path" (datum-string path))
                                    (cons "role" (construction-role tree path))
                                    (cons "node" (short-text (datum-string (ast-datum node)) 160)))
                              (if scheme-syntax? (list (cons "syntax_role" (symbol->string (scheme-node-role tree path)))) '())
                              (if (eq? (node-kind node) 'spell)
                                  (list (cons "prefix" (vector-ref node 3))
                                        (cons "prefix_length" (string-length (vector-ref node 3)))) '())
                              (let ((problem (or construction-issue
                                                 (and (string=? action "construct") (spelling-problem node max-literal)))))
                                (if problem (list (cons "construction_problem" problem)) '())))))
              (cons "criteria"
                    (apply object (map (lambda (option)
                                         (cons (car option) (if (string? (cdr option)) (cdr option)
                                                               (constructor-description (cdr option) (null? path) tree symbols)))) options)))))
    (define (install! path replacement action)
      (let* ((before (ast-at tree path)) (candidate (ast-replace tree path replacement)))
        (guard (ex (else (checkpoint 'size-limit) (raise ex)))
          (validate-ast candidate max-nodes max-depth))
        (set! tree candidate)
        (record (list 'edit (object (cons "path" (datum-string path)) (cons "action" action)
                                   (cons "before" (datum-string (ast-datum before)))
                                   (cons "after" (datum-string (ast-datum replacement)))
                                   (cons "changed" (not (equal? before replacement))))))))
    (define (remember-abandonment! path action)
      (let ((entry (object (cons "path" (datum-string path)) (cons "action" action)
                           (cons "source" (short-text (datum-string (ast-datum (ast-at tree path))) 240)))))
        (set! history (take-up-to (cons entry history) 8))
        (record (list 'abandoned entry))))
    (define (backtrack-options path)
      ;; Keep even unusually deep trees within the API's 255-choice limit.
      ;; Farther ancestors remain reachable through repeated backtracking.
      (map (lambda (up)
             (cons (string-append "up:" (number->string up))
                   (string-append "Rebuild ancestor " (datum-string (take-up-to path (- (length path) up)))
                                  " from a hole, discarding its subtree.")))
           (append (integers-from 1 (min 254 (length path)))
                   (if (> (length path) 254) (list (length path)) '()))))
    (define (backtrack! paths)
      (if (null? paths) '()
          (let* ((questions (apply object
                              (map (lambda (path)
                                     (cons (datum-string path)
                                           (question "backtrack" path (ast-at tree path) (backtrack-options path)))) paths)))
                 (answers (ask "backtrack" questions))
                 (targets (map (lambda (path)
                                 (let* ((choice (field (field answers (datum-string path)) "choice"))
                                        (up (string->number (substring choice 3 (string-length choice)))))
                                   (take-up-to path (- (length path) up)))) paths))
                 (outermost '()))
            ;; Ancestor replacements dominate overlapping requests. Decide all
            ;; targets before changing the tree so no answer uses a stale path.
            (for-each (lambda (target)
                        (unless (or (member target outermost)
                                    (any-prefix? (select (lambda (p) (not (equal? p target))) targets) target))
                          (set! outermost (cons target outermost)))) targets)
            (for-each
              (lambda (target)
                (record (list 'backtrack
                          (object (cons "target" (datum-string target))
                                  (cons "requested_from" (list->vector (map datum-string
                                    (select (lambda (path) (prefix? target path)) paths)))))))
                (remember-abandonment! target "backtrack")
                (install! target (hole) "backtrack")) (reverse outermost))
            outermost)))
    (define (any-prefix? paths path)
      (and (pair? paths) (or (prefix? (car paths) path) (any-prefix? (cdr paths) path))))
    (define (complete-descent!)
      (let loop ((recent '()))
        (let* ((frontier (ast-frontier tree)) (snapshot (ast-construction-key tree))
               (visits (length (select (lambda (previous) (equal? snapshot previous)) recent))))
          (unless (null? frontier)
            ;; Repeated restart/backspace decisions can return to the exact
            ;; same AST forever. Ask the model for a larger repair scope on the
            ;; third visit; this is recovery, not a pass/call cutoff or approval.
            (if (and (>= visits 2) (pair? (caar frontier)))
                (begin
                  (set! construction-issue "Construction revisited the identical AST shape three times. Choose an ancestor to rebuild instead of repeating the token cycle.")
                  (record (list 'construction-cycle (object (cons "path" (datum-string (caar frontier)))
                                                            (cons "source" (datum-string (ast-datum tree))))))
                  (backtrack! (list (caar frontier)))
                  (set! construction-issue #f)
                  (checkpoint 'constructing)
                  (loop '()))
            ;; Recompute the frontier after each batch, since new names and
            ;; structure may change what later construction decisions can see.
            (let* ((batch (car (batches frontier batch-size)))
                   (plans (map (lambda (region)
                                 (let* ((raw (ast-options tree (car region) symbols literals
                                                          max-depth max-width max-literal))
                                        (options (append
                                                 (if scheme-syntax? (scheme-syntax-options tree (car region) symbols raw) raw)
                                                 (if (null? (car region)) '()
                                                     '(("backtrack" backtrack))))))
                                   (when (null? options)
                                     (checkpoint 'literal-limit) (error "no valid construction choices" (car region)))
                                   (list (car region) (cadr region) options))) batch))
                   (questions
                    (apply object
                      (map (lambda (plan) (cons (datum-string (car plan))
                                               (question "construct" (car plan) (cadr plan) (caddr plan)))) plans)))
                   (answers (ask "construct" questions))
                   (backtracked
                    (backtrack! (map car (select (lambda (plan)
                      (equal? "backtrack" (field (field answers (datum-string (car plan))) "choice"))) plans)))))
              (for-each
                (lambda (plan)
                  (let* ((path (car plan)) (node (cadr plan))
                         (label (field (field answers (datum-string path)) "choice")))
                    (cond ((string=? label "backtrack"))
                          ((any-prefix? backtracked path)
                           (record (list 'discarded-choice (object (cons "path" (datum-string path)) (cons "choice" label)))))
                          (else
                           (when (string=? label "restart") (remember-abandonment! path "restart"))
                           (let* ((constructor (cdr (assoc label (caddr plan))))
                                  (replacement (ast-construct constructor node (null? path) hole)))
                             (install! path replacement (string-append "construct " label))))))) plans)
              (checkpoint 'constructing)
              (loop (take-up-to (cons snapshot recent) 32))))))))
    (define (edit-options path)
      (let* ((node (ast-at tree path)) (kind (node-kind node)) (children (node-children node))
             (size (length children)))
        (append
          '(("retain" . "Leave unchanged for now; this is NOT a keep approval.")
            ("replace" . "Rebuild this subtree from a new hole."))
          (map (lambda (i) (cons (string-append "descend:" (number->string i))
                                 (string-append "Make a smaller edit inside child " (number->string i))))
               (integers-from 0 size))
          (if (memq kind '(program list vector))
              (append
                (if (< size max-width)
                    '(("append" . "Append a new child hole.") ("prepend" . "Prepend a new child hole.")) '())
                (map (lambda (i) (cons (string-append "delete:" (number->string i))
                                       (string-append "Remove child " (number->string i))))
                     (integers-from 0 size))) '()))))
    (define (revise! paths)
      (unless (null? paths)
        (let* ((batch (car (batches paths batch-size)))
               (rest (list-tail paths (length batch)))
               (questions (apply object
                            (map (lambda (path)
                                   (cons (datum-string path)
                                         (question "revise" path (ast-at tree path) (edit-options path)))) batch)))
               (answers (ask "revise" questions))
               (descents '()))
          (for-each
            (lambda (path)
              (let* ((action (field (field answers (datum-string path)) "choice"))
                     (node (ast-at tree path)) (children (node-children node)))
                (cond
                  ((string=? action "retain") (record (list 'retained path)))
                  ((string=? action "replace")
                   (remember-abandonment! path "replace") (install! path (hole) action))
                  ((member action '("append" "prepend"))
                   (let ((new (hole)))
                     (install! path (node-with-children node
                                     (if (string=? action "append") (append children (list new)) (cons new children))) action)))
                  ((equal? (substring action 0 7) "delete:")
                   (let ((index (string->number (substring action 7 (string-length action)))))
                     (remember-abandonment! (append path (list index)) "delete")
                     (install! path (node-with-children node
                                      (map cadr (select (lambda (x) (not (= index (car x))))
                                                        (map-indexed list children)))) action)))
                  (else
                   (let ((index (string->number (substring action 8 (string-length action)))))
                     (set! descents (cons (append path (list index)) descents))
                     (record (list 'edit-descent path index))))))) batch)
          (checkpoint 'revising)
          (revise! (append (reverse descents) rest)))))
    ;; Internal definitions precede expressions for portable R7RS expansion.
    ;; Pass/call budgets are optional (zero means unlimited). Structural bounds
    ;; still apply so a malformed or runaway candidate cannot grow indefinitely.
    (for-each (lambda (n) (unless (and (integer? n) (exact? n) (>= n 0)) (error "invalid generation budget" n)))
              (list max-passes max-calls))
    (for-each (lambda (n) (unless (and (integer? n) (exact? n) (> n 0)) (error "invalid generation limit" n)))
              (list max-nodes max-depth max-width max-literal batch-size))
    (when (> max-width 96) (error "max width must be at most 96"))
    (let ((ids (validate-ast tree max-nodes max-depth)))
      (unless (and (integer? next-id) (> next-id 0) (all? (lambda (id) (< id next-id)) ids))
        (error "invalid checkpoint next-id")))
    (record (list 'pass-start 1 (if (field config "ast" #f) "Resume and recheck the saved AST." "Start with an empty program: one root hole.")))
    (checkpoint 'start)
    (complete-descent!)
    (let pass ()
      (set! feedback (assess (ast-datum tree)))
      (checkpoint 'checking)
      (record (list 'assessment feedback (ast-datum tree)))
      (unless (and (equal? tree confirmed-tree) (equal? feedback confirmed-feedback) (equal? history confirmed-history))
        (record (list 'invalidate-confirmations (length confirmed-paths)))
        (set! confirmed-tree tree) (set! confirmed-feedback feedback) (set! confirmed-history history)
        (set! confirmed-paths '()))
      (record (list 'reuse-confirmations (length confirmed-paths)))
      (let ((regions (ast-regions tree)) (rejected '()))
        (for-each
          (lambda (batch)
            (let* ((questions
                    (apply object
                      (map (lambda (region)
                             (cons (datum-string (car region))
                                   (question "confirm" (car region) (cadr region)
                                             '(("keep" . "No change wanted in this context.")
                                               ("rebake" . "Reconsider this subtree."))))) batch)))
                   (answers (ask "confirm" questions)))
              (for-each (lambda (region)
                          (let ((path (car region)))
                            (if (equal? "keep" (field (field answers (datum-string path)) "choice"))
                                (set! confirmed-paths (cons path confirmed-paths))
                                (set! rejected (cons path rejected))))) batch)))
          (batches (select (lambda (region) (not (member (car region) confirmed-paths))) regions) batch-size))
        (record (list 'pass pass-number (length regions) rejected feedback))
        (if (and (null? rejected) (= (field feedback "passed") (field feedback "total")))
            (begin (checkpoint 'settled)
                   (list (cons 'source (ast-datum tree)) (cons 'ast tree) (cons 'next-id next-id)
                         (cons 'passes pass-number) (cons 'calls calls) (cons 'feedback feedback)))
            (begin
              (when (and (> max-passes 0) (>= pass-number max-passes))
                (checkpoint 'pass-limit) (error "pass limit reached without convergence" max-passes))
              (set! pass-number (+ pass-number 1))
              (record (list 'pass-start pass-number
                            (if (null? rejected) "Acceptance tests failed despite approvals; revise the program."
                                "Jev requested changes; choose edits at the outermost rejected subtrees, descending for local fixes.")))
              ;; Do not starve a rejected parent by endlessly repairing its
              ;; leaves. The model can choose descend instead of rebuilding it.
              (let ((targets (if (null? rejected) (list '())
                                 (select (lambda (path)
                                           (not (any-prefix? (select (lambda (other) (not (equal? path other))) rejected)
                                                             path))) rejected))))
                (revise! targets))
              (complete-descent!)
              (pass)))))))
