;; One append-only JSONL file per execution. Flush after every event, including
;; the request BEFORE starting network I/O. No credentials enter this layer.
(define (make-trace path mode input-rate output-rate . observers)
  (let ((port (open-output-file path)) (sequence 0)
        (started (current-milliseconds)) (calls 0) (responses 0)
        (input 0) (output 0) (metered 0) (http-attempts 0) (http-failures 0)
        (last-input 0) (last-output 0) (last-calls 0) (last-metered 0)
        (last-http-failures 0) (last-duration 0) (active-pass #f)
        (active-call #f) (call-started 0))
    (define (cost in out)
      (/ (+ (* in input-rate) (* out output-rate)) 1000000.0))
    (define (token-count? n) (and (integer? n) (>= n 0)))
    (define (pass-metrics duration)
      (let ((pass-input (- input last-input)) (pass-output (- output last-output))
            (pass-calls (- calls last-calls)))
        (object (cons "calls" pass-calls)
                (cons "reported_input_tokens" pass-input) (cons "reported_output_tokens" pass-output)
                (cons "reported_total_tokens" (+ pass-input pass-output))
                (cons "duration_ms" (- duration last-duration))
                (cons "estimated_usd_for_reported_usage" (cost pass-input pass-output))
                (cons "usage_complete" (and (= pass-calls (- metered last-metered))
                                            (= http-failures last-http-failures))))))
    (define (emit event)
      (set! sequence (+ sequence 1))
      (let ((packet (apply object
         (append (list (cons "seq" sequence) (cons "unix_seconds" (current-seconds))
                       (cons "elapsed_ms" (- (current-milliseconds) started)))
                 event))))
        (json-write packet port)
        (newline port) (flush-output-port port)
        (for-each (lambda (observer) (observer packet)) observers)))
    (define (record event)
      (let ((kind (car event)))
        (when (eq? kind 'pass-start) (set! active-pass (cadr event)))
        (case kind
          ((rates)
           (set! input-rate (cadr event)) (set! output-rate (caddr event))
           (emit (object (cons "event" "rates")
                         (cons "input_usd_per_million" input-rate)
                         (cons "output_usd_per_million" output-rate))))
          ((request)
           (set! calls (+ calls 1))
           (set! active-call (cadr event)) (set! call-started (current-milliseconds))
           (emit (object (cons "event" "request") (cons "call" (cadr event))
                         (cons "state" (caddr event)) (cons "questions" (cadddr event)))))
          ((response)
           (set! responses (+ responses 1))
           (let* ((response (caddr event)) (usage (field response "usage" #f)))
             (when (and usage (token-count? (field usage "input_tokens" #f))
                        (token-count? (field usage "output_tokens" #f)))
               (set! metered (+ metered 1))
               (set! input (+ input (field usage "input_tokens")))
               (set! output (+ output (field usage "output_tokens"))))
             (emit (object (cons "event" "response") (cons "call" (cadr event))
                           (cons "duration_ms" (if (pair? (cdddr event)) (cadddr event)
                                                  (- (current-milliseconds) call-started)))
                           (cons "response" response)))))
          ((completion-failed)
           (emit (object (cons "event" "completion-failed") (cons "call" (cadr event))
                         (cons "duration_ms" (caddr event)) (cons "error" (cadddr event)))))
          ((http-attempt)
           (set! http-attempts (+ http-attempts 1))
           (emit (object (cons "event" "http-attempt") (cons "call" active-call) (cons "details" (cadr event)))))
          ((http-result)
           (when (not (<= 200 (field (cadr event) "status" 0) 299))
             (set! http-failures (+ http-failures 1)))
           (emit (object (cons "event" "http-result") (cons "call" active-call) (cons "details" (cadr event)))))
          ((test-case test-build-error)
           (emit (object (cons "event" (symbol->string kind)) (cons "result" (cadr event)))))
          ((pass)
           ;; Pass 1 includes initial descent. Later passes include revisions
           ;; made after the preceding review, plus tests and confirmation.
           (let* ((duration (- (current-milliseconds) started))
                  (metrics (pass-metrics duration)))
             (emit (object (cons "event" "pass") (cons "number" (cadr event))
                           (cons "regions" (caddr event))
                           (cons "rejected_paths" (list->vector (map datum-string (cadddr event))))
                           (cons "feedback" (car (cddddr event)))
                           (cons "metrics" metrics)
                           (cons "cumulative_estimated_usd_for_reported_usage" (cost input output))))
             (set! last-input input) (set! last-output output) (set! last-calls calls)
             (set! last-metered metered) (set! last-http-failures http-failures)
             (set! last-duration duration)
             (set! active-pass #f)
             metrics))
          (else
           ;; Scheme data preserves paths, dotted pairs and full source exactly.
           (emit (object (cons "event" (symbol->string kind))
                         (cons "data_scheme" (datum-string (cdr event)))))))))
    (define (finish status)
      (let ((summary
             (object
              (cons "event" "summary") (cons "status" status) (cons "mode" mode)
              (cons "calls" calls) (cons "responses" responses)
              (cons "http_attempts" http-attempts) (cons "http_failures" http-failures)
              (cons "reported_input_tokens" input) (cons "reported_output_tokens" output)
              (cons "reported_total_tokens" (+ input output))
              (cons "duration_ms" (- (current-milliseconds) started))
              (cons "partial_pass" (or active-pass 'null))
              (cons "partial_pass_metrics" (and active-pass (pass-metrics (- (current-milliseconds) started))))
              (cons "usage_complete" (and (= calls metered) (= http-failures 0)))
              (cons "input_usd_per_million" input-rate)
              (cons "output_usd_per_million" output-rate)
              (cons "estimated_usd_for_reported_usage"
                    (cost input output))
              (cons "pricing_source" "https://typesafe.ai/blog/introducing-system-one-models-and-jev")
              (cons "pricing_checked" "2026-09-17"))))
        (emit summary) (close-output-port port) summary))
    (values record finish)))
